docs/.vuepress/components/MapBasicVector.vue
docs/.vuepress/components/MapTooltip.vue
docs/.vuepress/config.js
docs/collection/README.md
docs/collection/map-tooltip.md
packages/map-basic/src/MapBasic.vue
packages/map-basic/vue.config.js
packages/map-tooltip/.browserslistrc
packages/map-tooltip/.editorconfig
packages/map-tooltip/.eslintrc.js
packages/map-tooltip/.gitignore
packages/map-tooltip/README.md
packages/map-tooltip/babel.config.js
packages/map-tooltip/package.json
packages/map-tooltip/src/MapToolTip.vue
packages/map-tooltip/src/main.js
packages/map-tooltip/vue.config.js

This extracts the tooltip element to a different package, as it includes Vuetify and should not be bundled with the map-basic package.

Extract tooltip

---

packages/map-tooltip/README.md
packages/map-tooltip/src/MapToolTip.vue

probably needs some docs.
`:propertiesFilter` expects an array like this: 
```
[
{
field_name: "ori_parcel_id",
display_name: "SL_ID",
type: "string"
},
{
field_name: "colour",
display_name: "Conformance",
type: "legend/color"
},
{
field_name: "ori_crop_id",
display_name: "SNAR_CODE",
type: "reference/crop"
}
],
```

allow passing a property filter to the tooltip

---

elements/chart/src/interface.ts

This PR changes the way the iframe is created, instead of having an iframe that points to the hosting location, the iframe is crated locally and the hosted HTML is parsed and used as iframe content. This allows the iframe to run locally and use the same origin/referer/cookies as the host application and prevents CORS/authentication errors.
The host has also been changed from `unpkg` to `githack`.
not sure if this is the cleanest way to do this, and how configurable we want to make this.

fix(WIP): build local iframe using remote assets

---

elements/map/examples/index.html
elements/map/examples/layers.json
elements/map/main.ts
elements/map/package.json
elements/map/src/generate.ts
package-lock.json

This PR introduces parsing of a custom JSON format to generate layers. The basic structure of the layer JSON is:
```
[
{
"type": "<OL layer module type",
[...additional layer parameters]
"source": {
"type": "<OL source module type",
[...additional source parameters]
} 
}
]
```
Style functions need to be passed as an Object with the key `function`, and can have access to the Feature with the pattern `"(feature) => <your code here accessing feature>"`
Example of a successfully rendering layer array: 
```
[
{
"type": "Vector",
"background": "#1a2b39",
"myCustomProperty": "foo",
"source": {
"type": "Vector",
"url": "https://openlayers.org/data/vector/ecoregions.json",
"format": "GeoJSON"
},
"style": {
"function": {
"fill": {
"type": "Fill",
"color": "(feature) => feature.get('COLOR')"
}
}
} …
```

Parse layers from JSON

---

elements/map/main.ts
elements/map/src/select.ts

This PR sets the pointer-events for the map tooltip container to `none`. This can be still overridden if need be by explicitly setting a div inside the tooltip template to e.g. `pointer-events: all`.

Default tooltip pointer events to none

---

elements/timecontrol/src/main.ts

This PR makes sure that the original TileUrlFunction (responsible for getting the correct tile code) is not altered along the way, thus creating memory leaks. 
The `render` function is called every time step, i am uncertain if this is the correct behaviour, or if this is due to the testing setup.
Fixes https://github.com/EOX-A/EOxElements/issues/111

fix: set original tileUrlFunction only once

---

elements/map/src/controls.ts
elements/map/test/controls.cy.ts

This PR implements the controls as JSON. The Key of each property is the name of the control, the property itself represents the `options` of the ol-control.
If the control has a `layers`-Option (e.G. the `OverviewMap`), a JSON is expected, in the same way as when defining layers. Those layers will get parsed and will be added to the control only. The test is updated to display an `OverviewMap`-Control with OSM Tiles, which are not represented in the main map.

Controls as JSON

---

elements/itemfilter/src/main.ts

This PR fixes an issue where the results aggregation would fail if the aggregation property was not present within the filter properties.

Check if filter property actually exists

---

elements/layercontrol/README.md
elements/layercontrol/src/main.ts

This PR deprecates the attachTo method and prefers the "for" attribute. Question is if we still want to have the attachTo method in the readme.
This would require the apps using vanilla OL to add the map instance to the DOM object.

Proposal: deprecate attachTo method

---

elements/layercontrol/README.md
elements/layercontrol/index.html
elements/layercontrol/src/main.ts
elements/layercontrol/test/_mockMap.ts
elements/layercontrol/test/general.cy.ts

This PR implements a simple change to enable the subsections in the layer control to pre-expand if a flag is present in the layer config, as described in #184

Pre-expanded subsections using new `layerControlExpanded` layer attribute

---

elements/map/index.html
elements/map/main.ts
elements/map/src/controls.ts
elements/map/src/generate.ts
elements/map/src/select.ts
elements/map/test/hoverInteraction.cy.ts
elements/map/test/selectInteraction.cy.ts
elements/map/test/utils/events.ts

This PR introduces updates to the "Selection"-functionality (#194) and some refactoring of the map-element.
Selecting a feature does not work with the normal "Select"-Interaction. The `addSelect`-method of the map-element now creates a listener for the given event type (`click` or `pointermove`, defaulting to `click`) and creates an unmanaged layer to display the selected feature. That has the same source as the original layer, much like the `select`-interaction does internally, but can be styled freely, e.g. via flat styles. This also removes the hassle of working with `setFeatureState` (#193).
Additionally to the tooltip and the condition, an optional `idPoperty` can be defined (see the VectorTile-Test of `selectInteraction.cy.ts`), in case the native ID of the features are not stable …

Map Selection

---

elements/layercontrol/index.html
elements/layercontrol/src/main.ts
elements/layercontrol/src/style.eox.ts

This PR contains changes which ensure that long names render nicely and don't affect the surroundings.

Make long layer names render nicely in LayerControl

---

elements/itemfilter/README.md
elements/itemfilter/index.html
elements/itemfilter/src/filters/_expandcontainer.ts
elements/itemfilter/src/main.ts
elements/itemfilter/test/general.cy.ts

This PR implements two new Boolean config options for the item filter called `expandMultipleFilters` and `expandMultipleResults` which allow having multiple accordeons expanded at the same time if set. If unset, each opening of a new accordeon will close all other ones. This happens independently for each of the accordeon sets.
Closes #174 
https://github.com/EOX-A/EOxElements/assets/94269527/95723ecc-1172-4a16-a9f0-2fe9aabe5c07

Configurable single panel expansion for accordions

---

elements/map/main.ts
elements/map/src/layer.ts
elements/map/test/groupLayer.cy.ts

This PR is based in the ideas listed in #151. In order to get all the layers inside groups, but also the group layers itself, a function `getFlatLayersArray` was created. Maybe we want to expose this helper function, as filtering for attributes, but also non-property-based attributes (like `visible` to get all visible layers) would be 1-liners in the parent application?
The `getLayerById` function remained mostly unchanged, as it contains some special logic for mapbox-layers, which may or may not be used in the future. It currently also throws an error, which was useful when testing, but maybe it should just return `undefined` instead?
@silvester-pari currently the `generate`- function does a `Array.reverse` on the layers array, is there a certain reason for that? the added test does not …

get layer inside group

---

elements/layercontrol/src/main.ts
elements/layercontrol/src/style.eox.ts
elements/layercontrol/src/style.ts

To help contain the children of menu entries, especially those with many sub-items coming from, for example, a STAC catalogue, this style PR limits the height of sublists and makes sure they are appropriately sized for different viewport sizes.
https://github.com/EOX-A/EOxElements/assets/94269527/e6ecfbcb-fd86-4b79-b1fa-278a911628b1
Closes #218

Make menu subentries scrollable if they cross a length threshold

---

elements/map/index.html
elements/map/src/select.ts
elements/map/src/tooltip.ts
elements/map/test/hoverInteraction.cy.ts

This PR introduces some enhancements for the eox-map-tooltip:
- it allows passing native OL parameters to the Overlay
- it adds some default styling of the tooltip component
- it adds positioning of the tooltip (top-left/right, bottom-left/right) depending on the mouse position within the map
- it adds the functionality to override the rendering of the feature properties.

Tooltip enhancements

---

elements/map/index.html
elements/map/main.ts
elements/map/package.json
elements/map/src/compare.ts
elements/map/src/draw.ts
elements/map/src/generate.ts
elements/map/src/layer.ts
elements/map/src/select.ts
elements/map/src/tooltip.ts
elements/map/test/drawInteraction.cy.ts
elements/map/test/drawInteraction.json
elements/map/test/general.cy.ts
elements/map/test/groupLayer.cy.ts
elements/map/test/hoverInteraction.cy.ts
elements/map/test/imageWmsLayer.cy.ts
elements/map/test/selectInteraction.cy.ts
elements/map/test/vectorLayer.cy.ts
package-lock.json

This PR upgrades to ol 8 (which brings native style expressions) and improves the use of TypeScript in the Map Element.
The removal of the unneeded generic `Function`-Typing in `main.ts` allows us to receive the correct types in the parent application.
`layer` and `source` types are now done manually, defining all relevant types of layers and sources as strings. Before TS expected actual ol objects, which was not the intention.
The options-objects from `ol` can be utilised by importing the type (e.g. `import('ol/interaction/Draw').Options`), and adapting them for our needs, either by adding properties via the `&` operator and overloading the object with new properties, or omitting some properties via `Omit`, or doing both to change the type of a property.

chore: improve typing

---

elements/layercontrol/layercontrol.stories.js
elements/layercontrol/package.json
elements/layercontrol/src/main.ts
elements/layercontrol/test/_mockMap.ts
elements/layercontrol/test/general.cy.ts
elements/layercontrol/test/layersUpdate.cy.ts
package-lock.json

This PR introduces
- a renaming of the expand layer property: `layerControlExpanded` now is ``layerControlExpand` in order to harmonize with the other present-tense properties
- a new feature that pushes a layer back into the optional layers list instead of removing it from the collection

Layercontrol v0.6.8

---

elements/map/src/generate.ts
elements/map/src/select.ts

This PR handles the in #267 described that some attributes did not get carried over from the original layer when creating the select-style-layer, as a (too much) simplified layer generation method was used. Now the same definition-JSON is used, only simplifying the Source as well as overriding the style and id.
Additionally, the type of `EoxLayer` was crudely improved, to underline the fact that ol-layer-attributes like `minZoom` are in fact allowed properties for EoxLayers.

fix: select style layer attributes

---

elements/map/map.stories.js

This PR adds stories of the `EOxMap` element. 
Right now, functionality that is set via methods or properties after the map is mounted (like selection, map sync, etc) are set via storybook [play functions](https://storybook.js.org/docs/react/writing-stories/play-function), as that is basically callback of the render function, if i understand correctly. While this works for single stories, these play functions are not called in the `documentation`-tab of storybook, and the code, which is the relevant part of the documentation, is also not displayed.
I'm not sure what the best solution to this is, or if this just displays some anti-pattern when designing web components. We can always duplicate the code snippets and display them in storybook inside the render function, but that does not fix …

chore: base structure of map stories

---

elements/layercontrol/layercontrol.stories.js
elements/layercontrol/src/components/layer.js
elements/layercontrol/src/components/layerConfig.js
elements/layercontrol/src/components/layerGroup.js
elements/layercontrol/src/components/layerList.js
elements/layercontrol/src/components/layerTools.js
elements/layercontrol/src/components/optionalList.js
elements/layercontrol/src/components/tabs.js
elements/layercontrol/src/main.js

This PR introduces: 
1. `styleOverride` property to the `eox-layercontrol`. It gives the ability to override the current styles of the element. 
2. `noShadow` property to  `eox-layercontrol-layer-list`,`eox-layercontrol-layer-group`,`eox-layercontrol-layer`,`eox-layercontrol-layerconfig`, `eox-layercontrol-optional-list`, and `eox-layercontrol-tabs`. The property allows you to override the operation that creates a shadow root in those elements, and it's set to a default value of `true`.

feat: StyleOverride & noShadow 

---

elements/map/src/select.ts
elements/map/test/hoverInteraction.cy.ts

This PR implements the in #351 documented issue of sticky tooltips in the hover-selection. 
closes #351

feat: remove the overlay when pointer leaves

---

elements/layercontrol/src/main.js

this PR closes #342; `eox-layercontrol-optional-list` gets updated after any layer removal.

fix: optional list update after layer removal

---

elements/stacinfo/package.json
elements/stacinfo/src/main.ts
elements/stacinfo/test/general.cy.js
package-lock.json

Using `allow-html` attribute or `allowHtml` property, rendering of HTML can be enabled.

feat: allow rendering HTML in properties via config

---

elements/itemfilter/src/autocomplete.ts
elements/itemfilter/src/chips.ts
elements/itemfilter/src/filters/text.ts
elements/itemfilter/src/inline.ts
elements/itemfilter/src/main.ts

this PR includes the following fixes for itemfilter inline mode:
- removing input text using backspace without deleting chips.
- removing input text on filter type selection.
- opening drop down on chip removal.
- commit text search using enter key.
- commit filter or reset filter choice using space bar.
- selecting checkbox of multiselect filter using enter key, after searching for the filter.

fix: inline mode improvements

---

elements/jsonform/package.json
elements/jsonform/src/custom-inputs/index.js
elements/jsonform/src/custom-inputs/minmax.js
elements/jsonform/src/main.js
elements/jsonform/src/style.eox.js
elements/layercontrol/layercontrol.stories.js
elements/layercontrol/package.json
elements/layercontrol/src/components/layerConfig.js
elements/layercontrol/src/components/layerTools.js
elements/layercontrol/src/helpers.js
elements/layercontrol/src/main.js
elements/map/src/generate.ts
package-lock.json

- Add `layer-config` with help of `tools`
- Pass `layerConfig` inside `eox-map` and `tools=['config']`
- Replaced old `layer-config` code.
- Add `minmax` custom input field 
- Update map url whenever `input` field's `value` change
<a href="https://www.loom.com/share/0cacf9226c0941918652419be6f7789a" target="_blank"><img src="https://cdn.loom.com/sessions/thumbnails/0cacf9226c0941918652419be6f7789a-with-play.gif" width="100%" /></a>

Feature: Layer Config 

---

.github/workflows/check_formatting.yml
.github/workflows/check_linting.yml
.github/workflows/release-please.yml
.github/workflows/run_tests.yml
package-lock.json
package.json

This PR introduces Node 20 for all CI pipelines, and sets the minimum required Node version for a `npm install` to `v20.9.0 (LTS)`.
It seems that all pipelines and scripts run normally, will do some more testing before merging.
https://nodejs.org/en/

chore: introduce node >20

---

elements/layercontrol/layercontrol.stories.js
elements/layercontrol/src/components/layerConfig.js
elements/layercontrol/src/helpers.js

- original `tileUrlFunction()` is called and then update it using layerConfig's `updateUrl()`

Fix: Handle `tileUrlFunction()` use case for `layerConfig`

---

elements/drawtools/drawtools.stories.js
elements/drawtools/src/main.js

This PR adds the `allowModify` property, which allows to configure if the drawn feature(s) should be modifiable after drawing or not.

feat: enable modify via property

---

elements/drawtools/drawtools.stories.js
elements/drawtools/src/main.js

This PR adds the `type` property, which allows to configure the draw type (Polygon, Box, Circle, Point, LineString).

feat: draw type property

---

elements/layercontrol/src/helpers.js
elements/layercontrol/test/_mockMap.js

This method of looping through the layers and adding/removing based on index seems to do the trick. It was a bit finnicky with the index as we have our layers reversed, but it seems to work.
Tested:

fix: loop through layers and remove/add via index

---

elements/layercontrol/src/components/layerList.js
elements/layercontrol/src/helpers.js

This solves the following issues for `eox-layercontrol-layer-list`:
1. sorting lists that contain layers that are not displayed.
2. sets `idProperty` & `titleProperty` if not assigned.

fix: sorting with optional & hidden layers

---

elements/map/src/generate.ts

This PR adds the missing synchronization of the layer zIndex to the `eoxLayer`.

fix: add missing zIndex sync

---

elements/drawtools/src/methods/draw/init-draw-layer.js

- The interaction check, previously included within `init-draw-layer.js`, has been implemented inside `addOrUpdateLayer()` through PR #476. Consequently, to prevent duplicate checks, we should eliminate the corresponding check from `init-draw-layer.js`. Failing to do so will result in an error due to redundant validation.

Fix: Remove interaction check from `drawtools`

---

.eslintrc
elements/map/README.md
elements/map/main.ts
elements/map/map.stories.js
elements/map/package.json
elements/map/src/generate.ts
elements/map/src/plugins/advancedLayersAndSources/formats.ts
elements/map/src/plugins/advancedLayersAndSources/index.ts
elements/map/src/plugins/advancedLayersAndSources/layers.ts
elements/map/src/plugins/advancedLayersAndSources/sources.ts
elements/map/test/stacLayer.cy.ts
elements/map/typings.d.ts
elements/map/vite.config.advancedLayersAndSources.ts
elements/map/vite.config.ts

This PR splits up OpenLayers `formats`, `layers` and `sources` to include only the most basic ones, while advanced ones can be added as a separate plugin. This is in order to reduce the bundle size for the most common use cases.
Included in the base bundle:
- Formats: `GeoJSON`, `MVT`
- Layers: `Group`, `Image`, `Tile`, `Vector`, `VectorTile`,
- Sources: `ImageWMS`, `OSM`, `Tile`, `TileWMS`, `Vector`, `VectorTile`, `WMTS`, `XYZ`
In order to use all formats, layers and sources provided by OpenLayers, import the plugin as well:
```
import "@eox/map/dist/eox-map-advanced-layers-and-sources.js"
import "@eox/map/dist/eox-map.js"
<eox-map [... GeoTIFF sources, STAC layers etc ...]></eox-map>
```
If the developer forgets to import the bundle but tries to use an advanced format, layer or source, …

feat!: extract advanced layers & sources into separate bundle

---

elements/map/src/generate.ts

This moves the definitions into the `createLayer` function, in order to avoid race conditions where `window.eoxMapAdvancedOlLayers` etc. are undefined at execution.

chore: move definition of available formats, layers and sources into function

---

elements/map/main.ts
elements/map/map.stories.js
elements/map/test/configObject.cy.ts

This PR adds a `config` property which is an alternative/short hand to define the map `controls`, `layers` and `view`. It is handy if the `eox-map` is used with vanilla JS or if an entire map config is to be fetched e.g. from an API or local storage.
```
<eox-map
.config=${{
controls: {
Zoom: {},
},
layers: [{ type: "Tile", source: { type: "OSM" } }],
view: {
center: [16.8, 48.2],
zoom: 9,
},
}}
></eox-map>
```
This is the same as if using this:
```
<eox-map
.controls=${{
Zoom: {},
}}
.layers=${[{ type: "Tile", source: { type: "OSM" } }]}
.center=${[16.8, 48.2]}
.zoom=${9}
></eox-map>
```
Closes #284.

feat: introduce config object

---

elements/itemfilter/itemfilter.stories.js
elements/itemfilter/src/filters/_filterTypes.d.ts
elements/itemfilter/src/filters/multiselect.ts
elements/itemfilter/src/filters/select.ts
elements/itemfilter/src/global.d.ts
elements/itemfilter/test/state.cy.ts

Introducing custom ordering function `sort` as a  property in `type: select` and `type: multiselect` filter objects. Closing #416

Feat: Custom ordering for select and multi select filters

---

elements/itemfilter/src/filters/multiselect.ts
elements/itemfilter/src/filters/select.ts
elements/itemfilter/src/selectionlist.ts
elements/itemfilter/test/general.cy.ts
elements/itemfilter/test/state.cy.ts

Introducing `noShadow` property in `eox-selectionlist` that enables it's rendering without a shadow root and giving access for `styleOverride` property of the `eox-itemfilter` to reach `eox-selectionlist` in primary (not inline) mode.

Fix: Itemfilter StyleOverride access to selectionlist

---

elements/layercontrol/test/layersUpdate.cy.js

```bash
Add new external WMS/XYZ and JSON Layer - addExternalLayers:
CypressError: Timed out retrying after 4000ms: `cy.find()` failed because the page updated as a result of this command, but you tried to continue the command chain. The subject is no longer attached to the DOM, and Cypress cannot requery the page after commands such as `cy.find()`.
```
- Your JS framework re-rendered asynchronously
- Your app code reacted to an event firing and removed the element
```js
cy.get(".search-icon").click();
cy.get(".add-layer-icon").first().click();
```
to (by adding ref - `@apibtn` to the async API button)
```js
cy.get(".search-icon").as("apibtn").click();
cy.get("@apibtn").should("not.be.disabled");
cy.get(".add-layer-icon").first().click();
```

Fix: Build fail due to async call

---

elements/layercontrol/src/components/addLayers.js
elements/layercontrol/src/components/layer.js
elements/layercontrol/src/components/layerConfig.js
elements/layercontrol/src/components/layerGroup.js
elements/layercontrol/src/components/layerList.js
elements/layercontrol/src/components/layerTools.js
elements/layercontrol/src/components/optionalList.js
elements/layercontrol/src/components/tabs.js

This PR sets all `noShadow` property setups to use `false` as default value. The reasoning is as follows: By default, the sub-components shall have a shadow root, so they can be easily used as standalone components in other circumstances. Just in the case of being integrated into the layercontrol, we want to override this and set `noShadow`  to true, skipping the shadow root creation. This enables an easier way to access deeply nested DOM elements for easier styling etc.

chore: initialize noShadow as false by default

---

elements/map/map.stories.js
elements/map/src/select.ts
elements/map/src/tooltip.ts

This PR adds the currently selected `Feature` as a second argument to the `propertyTransform` function in order to cover more complex transformation use cases.
Alongside this, more stories and documentation have been added to showcase usage of the tooltip.
Closes https://github.com/EOX-A/EOxElements/issues/541

feat: pass selection feature as second argument

---

elements/map/map.stories.js
elements/map/src/select.ts
elements/map/test/tooltip.cy.ts

This PR goes in a different direction than https://github.com/EOX-A/EOxElements/pull/555: when the select interaction is initialized, first check if an eox-map-tooltip was already instantiated on the map, if so, reuse that overlay, if not, create a new one.
This should fix the issue with not finding the DOM element, but means only one tooltip can exist per map.

fix: check if overlay was already instantiated before creating a new one

---

elements/map/src/select.ts

[Screencast from 2024-01-16 09:04:23.webm](https://github.com/EOX-A/EOxElements/assets/26576876/f54a5730-c523-4a1c-a3db-8df8382a9a84)
This PR introduces a check before setting the overlay position to `null`. This helps keeping the tooltipü visible if a user clicks on a featuer and then leaves the map with the mouse.
With this PR, only `pointermove` events will disable the tooltip when leaving the map - I am wondering if also other conditions should be checked? :thinking: See https://openlayers.org/en/latest/apidoc/module-ol_events_condition.html#~Condition

fix: keep tooltip visible if not emitted by pointermove

---

elements/layercontrol/src/components/layer-tools.js

This PR actually executes the code necessary in order to render the single action button.

fix: properly render single action button

---

elements/layercontrol/src/components/layer-tools.js
elements/layercontrol/src/helpers/layer-tools.js
utils/styles/button.ts

This PR replaces empty buttons (used for sorting the layer) with spans in order to fix [a bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=568313).
Fixes #580

fix: replace empty button to fix firefox sorting

---

elements/layercontrol/src/components/layer.js
elements/layercontrol/test/cases/general/disable-drag.js

This PR adds an additional way to sort layers by dragging them (dragging the sorting "tool" icon still works).

feat: allow sorting layers by dragging them

---

elements/layercontrol/src/helpers/check-properties.js
elements/layercontrol/src/methods/layer-list/first-updated.js

This PR adds an additional `requestUpdate()` after the initial `propertyCheck()`, to force the DOM to re-render. The reason for this is that SortableJS needs the layer `id` present in order to work correctly.
The `requestUpdate()` is only called in case it is needed, e.g. if the `id` or `title` were changed by the `propertyCheck()`.
Fixes #584.

fix: make sure a fallback layer id is rendered in time in order to support sorting

---

elements/jsonform/src/custom-inputs/index.js
elements/jsonform/src/main.js

Instead of importing the bundle, import the module, which allows tree-shaking.
Ref. https://github.com/json-editor/json-editor/issues/1470
```
dist/eox-jsonform.js  828.19 kB │ gzip: 144.86 kB
dist/eox-jsonform.umd.cjs  596.59 kB │ gzip: 127.46 kB
```
```
dist/eox-jsonform.js  421.60 kB │ gzip: 86.46 kB
dist/eox-jsonform.umd.cjs  328.16 kB │ gzip: 74.71 kB
```

chore: decrease bundle size of jsonform

---

elements/map/src/select.ts

This PR fixes a bug where the interaction was still firing events, even when it is not active.

fix: consider active inside listener

---

elements/timecontrol/src/main.ts
elements/timecontrol/timecontrol.stories.js

This pull request introduces a new `currentTime` property within the time control, which gets the currently selected time string of an `eox-timecontrol` element, for example like this:
```javascript
// Set the current time
timeControl.currentTime = '2022-12-26'
// '2022-12-26'
console.log(timeControl.currentTime)
```
Closes #608 
N/A

feat: add a `currentTime` property to get and set time programmatically

---

README.md
elements/layout/README.md
elements/layout/package.json
elements/layout/src/enums/index.js
elements/layout/src/enums/stories.js
elements/layout/src/enums/test.js
elements/layout/src/main.js
elements/layout/stories/gap.js
elements/layout/stories/grid.js
elements/layout/stories/index.js
elements/layout/stories/layout.stories.js
elements/layout/stories/primary.js
elements/layout/test/cases/index.js
elements/layout/test/cases/load-layout.js
elements/layout/test/cases/render-gap.js
elements/layout/test/cases/render-items-width.js
elements/layout/test/cases/render-items.js
elements/layout/test/general.cy.js
elements/layout/tsconfig.json
elements/layout/vite.config.js
package-lock.json
release-please-config.json

This is the initial release of the new `eox-layout` element. It should facilitate the creation of user interface layouts based on a 12/12 grid. Initial features:
- `eox-layout` and `eox-layout-item` elements
- `gap` attribute for `eox-layout`
- configurable for `eox-layout-item`: **x** (coordinate), **y** (coordinate), **w**(idth) and **h**(eight)
- it has basic reactivity, meaning once attributes change, the layout re-renders
Future evolution might include features such as creating a layout from JSON, responsive layouts etc.

feat: initial layout element setup

---

elements/drawtools/test/cases/click-discard-btn.js
elements/drawtools/test/cases/click-draw-btn.js
elements/drawtools/test/cases/load-drawtool.js

Fixed redundant Cypress `it()` from the `drawtools` test. No matter what was placed inside, Cypress used to pass every single `drawtools` test. It was fixed by removing the `it()` inside the test methods.
- #460

Fix: Redundant cypress `it()` from drawtools test case

---

elements/timecontrol/src/main.ts

Edit: after some discussion, we opted to just support param updates instead of maintaingin both tile-specific cases and other cases. This also removes the usage of OL-internal API (which we should do anyway). This setup is now much simpler, and for special/complicated cases we would use a STAC-based approach (e.g. each "time" entry is a separate STAC item with a self-contained visualization url).
~This adds support for non-tiled sources by checking if a `tileUrlFunction` exists. If not, it is assumed to be a non-tiled source, and the params are used instead. The reason behind this is that ImageWMS sources don't have a url loader function and generally use urls + params instead.~
~We could use url + params also for tiled sources, but with the current setup, we would allow deeper level …

feat: support non-tiled sources

---

elements/timecontrol/src/main.ts

This fix allows also using tiemcontrol with layers inside layer groups. It uses a copy of the `getFlatLayersArray` function from https://github.com/EOX-A/EOxElements/blob/main/elements/map/src/layer.ts#L25 as temporary solution, for a permanent solution see: https://github.com/EOX-A/EOxElements/issues/636

fix: support layers inside groups

---

elements/layercontrol/src/components/layer-group.js
elements/layercontrol/src/components/layer-list.js
elements/layercontrol/src/helpers/hide-layers-based-on-property.js
elements/layercontrol/src/helpers/index.js
elements/layercontrol/test/_mockMap.js
elements/layercontrol/test/cases/general/empty-groups.js
elements/layercontrol/test/cases/general/index.js
elements/layercontrol/test/general.cy.js

This PR supersedes https://github.com/EOX-A/EOxElements/pull/604. It hides the details marker for layer groups with no child layers. As this is a styling "opinion" it only applies to the "EOX styled" version (not to the unstyled one).
To trigger this, all child layers need to have the `layerControlHide` property set to `true`; it automatically hides the expand/contract icon on the parent group, this way it looks like a layer (but with a "group" icon).

feat: hide styled details marker if no children are in group

---

elements/layercontrol/src/components/layer-group.js
elements/layercontrol/test/cases/general/check-pre-open-section.js

This PR fixes a bug introduced by [the layercontrol refactor](https://github.com/EOX-A/EOxElements/pull/527/files#diff-0c0c4261c188b4fd751b2dbe16180cfaf498f1d0e312ce9915a952acd91a07fcR101), as the `layerControlExpand` boolean property [was always creating a "truthy" `open` attribute on the details](https://github.com/EOX-A/EOxElements/pull/527/files#diff-0c0c4261c188b4fd751b2dbe16180cfaf498f1d0e312ce9915a952acd91a07fcR112). In HTML, an attribute like e.g. `<details open="false"></details>` is still interpreted as "truthy" (as it is just a string). By using the `nothing` helper provided by lit, this can be mitigated (`nothing` removes the attribute completely).

fix: don't expand layer if `layerControlExpand` is falsy

---

elements/layercontrol/test/_mockMap.js
elements/layercontrol/test/cases/general/empty-groups.js
elements/layercontrol/test/cases/layer-update/check-if-layer-pushed-to-group.js
elements/layercontrol/test/cases/layer-update/check-layer-removed-from-group.js
elements/layercontrol/test/cases/layer-update/check-layer-removed-from-root.js

This PR fixes the order of the layers rendered in the mockmap, in order to behave more similarly to the real eox-map.

fix(test): mock map layer order

---

elements/timecontrol/src/main.ts
elements/timecontrol/test/cases/change-time.js

Suggested by @StefanBrand , `onTimeChange` sounded more like an event callback, hence the change. **This is a breaking change**.

chore!: rename event from onTimeChange to timeChange in `timecontrol`

---

elements/storytelling/src/main.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-slot.js
elements/storytelling/stories/storytelling.stories.js
elements/storytelling/test/cases/index.js
elements/storytelling/test/cases/load-markdown-slot.js
elements/storytelling/test/general.cy.js

- Allow users to pass markdown as an `inner-child` using slot and then generate html out of it.
```html
<eox-storytelling>
This is some [markdown](https://en.wikipedia.org/wiki/Markdown).
</eox-storytelling>
```
- By default `<slot>` will be hidden using `css` but able to access markdown using 
```javascript
this.shadowRoot.querySelector("slot")
```

Feat: Render markdown from default slot

---

elements/storytelling/stories/markdown-url.js

Hotfix for `markdownURL` issue in production because the github pages has a subfolder `/EOxElements`. And we were using `window.location.origin`, now it is replaced to `window.location.href.split("iframe.html")[0]`. It will work on both local and prod.

Fix: Markdown url pattern breaking on prod

---

.storybook/preview.js

When generating the autodocs code, Storybook scraps properties added via the lit `.<property>` syntax. The previous solution worked for some cases, but it
- wrongly applied args to the elements (the story element would get all args) and it
- applied args that weren't even used
The new approach goes through the raw lines line by line and tries to figure out which arg belongs to which element.

fix(docs): improve args/props rendering

---

elements/storytelling/src/enums/index.js
elements/storytelling/src/enums/plugin.js
elements/storytelling/src/main.js
elements/storytelling/src/markdown-it-plugin/index.js
elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-attr-comment.js
elements/storytelling/stories/storytelling.stories.js
elements/storytelling/test/cases/index.js
elements/storytelling/test/cases/load-markdown-attribute-comment.js
elements/storytelling/test/general.cy.js

- Added improved [markdown-it-decorate](https://github.com/rstacruz/markdown-it-decorate)
- Converted to ES6 
- Added comments 
- We can expand it in the future based on adding new features to it.
- Example markdown 
```markdown
Some text with red color 
```

Feat: Render attributes via comment tags 

---

elements/storytelling/src/main.js

This PR introduces a default general restriction for the width of `iframe`, `img` and `video` elements. These elements shouldn't break out of the page by default, and setting them to `max-width: 100%` helps contain them.
In case someone wants to explicitly override this default and set them larger, it will be possible using #700.
E.g. ``

fix(style): restrict `iframe`, `img`, `video` max width by default

---

elements/layercontrol/src/components/layer-config.js
elements/layercontrol/stories/layercontrol.stories.js

Remove import of @eox/jsonform from layercontrol
Bundle size before removal of `@eox/jsonform` package
```
dist/eox-layercontrol.js  547.90 kB │ gzip: 119.85 kB
dist/eox-layercontrol.umd.cjs  421.72 kB │ gzip: 102.76 kB
```
Bundle size after removal of `@eox/jsonform` package
Fixes #585

fix!: remove @eox/jsonform import from layercontrol

---

elements/itemfilter/itemfilter.stories.js
elements/itemfilter/src/main.ts
elements/itemfilter/test/general.cy.ts
elements/itemfilter/test/state.cy.ts

This PR introduces a reactive `items` property for setting items. Up until now, `eoxItemFilter.items` was only used to retrieve the current state, now it can also be set:
```
eoxItemFilter.items = [{...}]
```
Under the hood, this does the same as the `apply()` function; it's just more web component-like and easier to render in the storybook.
Implements https://github.com/EOX-A/EOxElements/issues/718.
Stories and tests have been updated accordingly.

feat: introduce reactive `items` property

---

elements/layercontrol/src/main.js
elements/layercontrol/src/methods/layer/input-click.js
elements/layercontrol/src/methods/layercontrol/layer-list-change.js
elements/layercontrol/test/cases/layer-update/check-layer-changed-event.js
elements/layercontrol/test/cases/layer-update/index.js
elements/layercontrol/test/layersUpdate.cy.js

This PR adds a generic `layerchange` event to `eox-layercontrol`. Currently it triggers when a layer's visibility is changed or the length of layers inside a group is changed; more events could be added in the future.
Usage:
```js
eoxLayerControl.addEventListener("layerchange", (e) => {
console.log(e.detail.get("id))  
console.log(e.detail.getVisible())
})
```

feat: dispatch layerchange event

---

elements/map/helpers.ts
elements/map/main.ts
elements/map/map.stories.js
elements/map/src/utils.ts
elements/map/test/configObject.cy.ts
elements/map/test/viewProjection.cy.ts

This PR brings the usage of projections, as described in #702.
Out-of-the-box, `EPSG:4326` is supported in addition to the standard `EPSG:3857`. Other projections can be used by calling the helper-function `registerProjection` first, including a name and proj4 definition string. These can be obtained by via services like [epsg.io](epsg.io), this must be handled by the parent application.
Switching the projection is possible by setting the `projection`-attribute. A new `view` is created when doing so, listener functions are moved over to the new view. It is important that set listeners retrieve the view via `evt.target`, instead of `this`.

feat: switch projections & allow advanced projections

---

elements/map/main.ts
elements/map/map.stories.js

This PR fixes an oversight that VectorLayers need a `refresh` on their source after changing the projection of the `view`.

fix: refresh source of VectorLayer after projection change

---

elements/layercontrol/src/components/layer-tools.js

Check if `layerConfig` prop is used before using the `<eox-layercontrol-layerconfig>` component
Fixes #734

fix: only use layerConfig element when layerConfig property is used

---

elements/storytelling/src/helpers/index.js
elements/storytelling/src/helpers/misc.js
elements/storytelling/src/main.js
elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js
elements/storytelling/stories/custom-element.js
elements/storytelling/stories/index.js
elements/storytelling/stories/storytelling.stories.js
elements/storytelling/test/cases/index.js
elements/storytelling/test/cases/load-custom-element.js
elements/storytelling/test/general.cy.js

- Add custom element using markdown `h2` (`#`) and `as` attribute in decorate 
- It will generate a custom element as per the value given in `as`
- `as` should always be in `kabab-case` otherwise it won't get generated.
- This PR will automatically generate custom elements and attributes used in markdown so that DOM sanitizer doesn't remove it from HTML code. 
```markdown
```
converts to - 
```html
<foo-bar text="foo-bar" class="block" id="foo"></foo-bar>
```
https://github.com/EOX-A/EOxElements/assets/10809211/5e559136-196b-4355-be15-e6611b11b76d

Feat: Replace `h2` tags via `as` attr

---

elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js

- Adding `h2` content as `title` for the section component.
```markdown
```
to html - 
```html
<esa-main-section title="EarthCODE Portal"></esa-main-section>
```

Feat: Add `h2` content as `title` attribute in sections 

---

elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js

This fix makes the changes implemented in https://github.com/EOX-A/EOxElements/pull/759 more robust, as it introducs a check if the title is actually present before accessing it.
This allows things as 
```md
```
without breaking.

fix: allow empty section titles

---

.github/workflows/run_tests.yml
cypress.config.ts

Suite of component tests being run is filtered based on elements which are affected by PR. The list of files changed is parsed from git diff. If cypress folder changed, all component tests are run.
New functionality is shown in Draft PR https://github.com/EOX-A/EOxElements/pull/758 which can be closed and branch deleted after this PR is merged.

chore(tests): run filtered suite of component tests when element changed

---

elements/storytelling/src/helpers/index.js
elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js
elements/storytelling/src/style.eox.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-map-section.js
elements/storytelling/stories/markdown-sections.js
elements/storytelling/stories/storytelling.stories.js
elements/storytelling/test/cases/index.js
elements/storytelling/test/cases/load-map-section.js
elements/storytelling/test/general.cy.js

- Added `eox-map` as a section to StoryTelling
```markdown
``` 
converted to - 
```html
<eox-map zoom="10" layers="[]"></eox-map>
```
- We can now add any custom element using `h2`, and it will dynamically pass the value according to the required data type.
- I created a render function that automatically identifies and parses attributes based on their data type. This is necessary because HTML is stored as a string, and LitElement cannot identify the desired data type on its own, as discussed during our MVP phase.
https://github.com/EOX-A/EOxElements/assets/10809211/e5a5e913-a9b2-442a-8e60-a38d23cd319c

Feat: Storytelling map section powered by @eox/map

---

elements/map/main.ts
elements/map/map.stories.js
elements/map/src/controls/Geolocation.ts
elements/map/src/controls/controls.css
elements/map/src/controls/controls.ts
elements/map/test/controls.cy.ts

This PR brings a custom Geolocation-control as defined in #562, that can be used just like any other `ol`-control. The user has to agree to the location-prompt by the browser, which will only show up when served via https (which is also true for testing, workarounds like ngrok or mkcert will be needed).
The `centerWhenReady`-prop will pan the view to the user position on the first update of the geolocator.
Rotation is not implemented by default, but the `heading`-property of the position feature is set, so by setting the `style`-property of the geolocation control a rotation get be set by accessing that property via style expressions.
(to enable tracking the heading, `highAccuracy` and `trackHeading` have to be set).
With `trackAccuracy` the accuracy feature will be shown in addition to …

feat: geolocation control

---

elements/map/main.ts

This PR adds some fallback values when parsing the config property in order to prevent breaking the map when things like `layers` or `controls` are omitted. Fixes #771.

fix: add fallback values if config properties are not defined

---

elements/storytelling/src/enums/index.js
elements/storytelling/src/enums/render.js
elements/storytelling/src/main.js
elements/storytelling/stories/markdown-attr-comment.js

- DOM Purify also removes some of the default tags from its purify HTML list and we need to pass it into a separate key called `ADD_TAGS` to enable it again and it is not part of custom tags. That's why `iframe` was not loading as it is part of sensitive tags.

Fix: Add default sensitive tags to dom purify list

---

elements/jsonform/src/main.js
elements/jsonform/test/cases/index.js
elements/jsonform/test/cases/load-jsonform-no-shadow.js
elements/jsonform/test/general.cy.js

This adds the `noShadow` functionality to jsonform, offering a way to create the element without shadow root. This is hand if the eox-jsonform is used as a sub-element where global styling is wanted.

feat: add no-shadow attribute/property

---

elements/itemfilter/itemfilter.stories.js
elements/itemfilter/src/main.ts

When setting `autoSpreadSingle` to true and a summary section only contains one entry this removes the summary section and shows directly the item.

feat: added autoSpreadSingle option to not show summary for single item groups

---

.github/workflows/run_tests.yml
elements/jsonform/jsonform.stories.js
elements/jsonform/src/helpers/editor.js
elements/jsonform/src/helpers/index.js
elements/jsonform/src/main.js
elements/jsonform/test/cases/index.js
elements/jsonform/test/cases/load-markdown.js
elements/jsonform/test/cases/trigger-change-event.js
elements/jsonform/test/general.cy.js

This PR implements SimpleMDE markdown editor for eox-jsonform (which uses [JSONEditor](https://github.com/json-editor/json-editor) under the hood).
It moves the creation of the JSONEditor to a centralized promise. Inside, an editor instance is first created, then once it is ready it is checked if at least one of the editors of the form uses markdown format. If not, it returns the editor instance. Otherwise, it destroys the instance again, loads the necessary SimpleMDE bundles, and creates a new editor instance instead, which is then returned.
This PR also adds a test that checks if the `update` event was triggered.

feat: markdown editor for fields with type "markdown"

---

elements/storytelling/src/components/editor.js

Since https://github.com/EOX-A/EOxElements/pull/810 introduces a markdown editor built into eox-jsonform, the dependency in eox-storytelling can be removed.

chore: remove simplemde cdn link

---

elements/storytelling/src/components/editor.js
elements/storytelling/stories/markdown-editor.js

This PR makes the storytelling editor compatible with noShadow, and hides/shows the editor using css once enbaled in order to not mess up rendering by lit.

fix(style): adapt styling to new editor

---

elements/jsonform/src/main.js

This PR restructures the editor creation and setters of schema/value in order to prevent unintended loops with the new asynchronous setup.

fix: prevent looping when loading external schema

---

.eslintrc
elements/stacinfo/src/helpers/index.ts
elements/stacinfo/src/helpers/properties.ts
elements/stacinfo/src/main.ts
elements/stacinfo/src/style.eox.ts
elements/stacinfo/stacinfo.stories.js
elements/stacinfo/stories/public/collection.json
utils/styles/button.css
utils/styles/button.ts

This PR adds some styling improvements to `eox-stacinfo`, especially how `ul`s and `link`s are rendered: The default style removal of `ul`s is gone but handled more on a case-by-case base. Links in `providers`, `assets` ands `links` are parsed from the `formatted` property and rendered as buttons.
Additional styling fixes have been added for `details`/`summary` rendering, harmonizing with how `eox-itemfilter` looks.
Also, a `tags` section has been introduced which allows specifying some properties as tags that are rendered in a chip-like manner.
Some things might be very opinionated and only suitable for `eodash`, but we'll iterate further.

fix(style): improve link rendering, tag rendering, details styling etc.

---

elements/map/src/generate.ts
elements/map/test/addOrUpdateLayer.cy.ts

This PR handles the Issue https://github.com/EOX-A/EOxElements/issues/732, where the second change was not properly detected. The problem was a bit tricky to find, but the solution quite simple, as the `_jsonDefinition`-object was simply not set correctly when updating a layer.

fix: update internal `_jsonDefinition`

---

elements/map/map.stories.js
elements/map/src/controls/Geolocation.ts

This PR implements the idea of a delayed browser popup (as described in https://github.com/EOX-A/EOxElements/issues/793). If the geolocation-control has the `centerWhenReady`-option set to `false`, the browser popup will appear only when the control button is clicked. As soon as the permission is granted, the map will pan to the newly created location feature (as described in [this comment](https://github.com/EOX-A/EOxElements/issues/793#issuecomment-2031528264)).
The story as been updated to display this behaviour, preventing the location-popup to show immediately when storybook is opened.

feat: delayed location popup for geolocation

---

elements/stacinfo/src/helpers/properties.ts
elements/stacinfo/src/main.ts
elements/stacinfo/src/style.eox.ts
elements/stacinfo/test/general.cy.js

This PR introduces some more styling fixes:
- single properties are now correctly rendered with only one column
- `description` is rendered in dedicated custom element with shadow root, avoiding CSS bleed
- `links`, `providers`, `assets` are rendered differently when used inside properties (`a` tags) or featured (`buttons`)

fix(style): improve property columns, description and link rendering

---

elements/storytelling/src/helpers/index.js
elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-hero-with-nav.js
elements/storytelling/stories/storytelling.stories.js
elements/storytelling/test/cases/load-hero-section.js

- If the first section is a `hero` section along with `show-nav` the navigation will stick below the `hero` section.
- If the first `hero` is after any other section, the navigation will be at top. The first `section` should be `hero`, then only it will work.
- If there are `multiple` hero sections then also first `hero` will be taken into account. 
```markdown
Bar description
```
https://github.com/EOX-A/EOxElements/assets/10809211/e29a1660-23f9-4a1e-a08d-17a8dfb17d2f

Feat: Sticky navigation after hero

---

elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/src/style.eox.js

- Increased padding between sections to `2rem` (`3rem` was looking to much white space)
- Increased first and last container section to `4rem` (Also it will go well with navigation)
- Added highlight current active nav (used `IntersectionObserver()`)
https://github.com/EOX-A/EOxElements/assets/10809211/0a94e107-161d-44ce-b06d-09aed84bcf7c

Fix: StoryTelling styling and highlight active nav item

---

elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-fallback.js
elements/storytelling/stories/storytelling.stories.js

- Added `fallback` mode so that non-renderable components can have a placeholder while writing markdowns in Github. 
```markdown
View on StoryTelling ![](fallback image) 
Description Here
```
| Github View | StoryTelling View |
| -------- | -------- |
| <img src="https://github.com/EOX-A/EOxElements/assets/10809211/4b0cca47-900e-47e7-ad0f-345cdfbe6e53" />     | <img src="https://github.com/EOX-A/EOxElements/assets/10809211/3090d4cd-a706-4ed0-aa32-ed26892a59c1" />     |

Feat: Dedicated fallback mode

---

elements/storytelling/src/style.eox.js

This fixes the z-index on the `navigation`.

fix(style): navigation z-index

---

elements/storytelling/src/helpers/render-html-string.js

- Threshold of `IntersectionObserver` acting weird and not able to trigger scroll change while intersecting the threshold. So converted  `Threshold` to `rootMargin` 
https://github.com/EOX-A/EOxElements/assets/10809211/b3b76519-afe4-4fa5-9849-3ac24c41092d

Fix: Change scroll logic from `threshold` to `rootMargin`

---

elements/stacinfo/src/helpers/properties.ts

This PR fixes https://github.com/EOX-A/EOxElements/issues/853. The negative lookahead in the regex was only looking for `href="`, but now has been extended to also ignore links preceded by `src="`.

fix: don't replace image src links

---

elements/stacinfo/src/main.ts

This PR fixes https://github.com/EOX-A/EOxElements/issues/854 by introducing the max-width style rule also to the shadow element used for the description.

fix: apply max-width to img, videos and iframes inside shadow element

---

elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js

- The custom section DOM was disrupted following the release of `StoryTelling` version `0.4.0` due to the introduction of the `hero section`.
- Wrapped section content, which has `as` and without a `mode` attribute, under the custom section specified by the `as` value.
```markdown
<div class="section-wrap">
<eox-main-section></eox-main-section>
<h4>Some content</h4>
<p>some content</p>
</div>
```
```html
<div class="section-wrap">
<eox-main-section>
<h4>Some content</h4>
<p>some content</p>
</eox-main-section>
</div>
```

Fix: Custom section dom structure

---

elements/storytelling/src/components/editor.js
elements/storytelling/src/helpers/editor.js
elements/storytelling/src/helpers/index.js
elements/storytelling/src/main.js
elements/storytelling/src/style.eox.js

- Auto saving added (Triggers every 2.5 seconds after editing editor)
- Stored inside `localstorage`
- Confirm prompt to load previous markdown again or not
- Works only when `editor` is enabled
https://github.com/EOX-A/EOxElements/assets/10809211/0cedaf54-006d-455c-b669-d6096476c048

Feat: Auto save in StoryTelling

---

elements/storytelling/src/style.eox.js

Changed CSS property for hiding editor to `display: none;` from `opacity: none;` (I don't know how this silly or funny thing happened 😅)

Fix: Hiding editor still shows button due to usage of opacity rather than display

---

elements/storytelling/src/components/editor.js
elements/storytelling/src/helpers/editor.js
elements/storytelling/src/helpers/index.js
elements/storytelling/src/main.js

- Markdown will only be saved in local storage if it has been modified either in the editor or through the "Add Section" popup.
- Markdown is saved under the `id` provided to `eox-storytelling`; otherwise, it is stored using the `default` key. This ensures that markdown is loaded only for the respective `ids`, preventing conflicts inside storytelling or even if using multiple storytellings inside an app.
- When a prompt is cancelled, the markdown associated with that particular `id` will be removed from local storage.
```json 
{
"default": "## Markdown for default without any id",
"id1": "## Markdown for id storytelling 1",
"id2": "## Markdown for id storytelling 2"
}
```
https://github.com/EOX-A/EOxElements/assets/10809211/7c1a901f-9015-4d07-8c1d-b984d8144619

Fix: Repetative prompt to load saved markdown 

---

elements/storytelling/src/components/editor.js
elements/storytelling/src/helpers/editor.js
elements/storytelling/src/helpers/index.js

- Validator was loading an empty screen due to delayed SimpleMDE package loading. Added a check to whether the SimpleMDE loaded or not. If loaded then only it hides the editor.

Fix: Editor loading issue 

---

elements/storytelling/src/helpers/validator.js

- "Group" layer validation missing from joi validator. That's why the below error occurred. Added alternative check for group layer and without group layers.

Fix: map layers schema

---

elements/map/main.ts
elements/map/test/configObject.cy.ts
package-lock.json
package.json

The previous config extraction was only considering type but was missing extraction of further properties, these have now been added for WMS, TiledWMS, XYZ config options.
For Vector sources it is not possible to retrieve the original style object (will possibly be fixed by OL)

feat: improved standard ol map config export

---

elements/map/main.ts
elements/map/test/configObject.cy.ts
package-lock.json
package.json

The previously implemented functionality relied on a JS feature which turns out not to be reliable. Since the previous version (1.8.0) can't be unpublished any longer, it will be marked as "deprecated", and this change will be released as 1.8.1 instead.

chore: revert non-working parts of config extraction

---

elements/map/main.ts

This PR introduces a small check to the `zoom` setter if the value is actually defined, as setting `undefined` resulted in a blank map.

fix: prevent reaction to undefined zoom

---

elements/jsonform/package.json
elements/jsonform/src/helpers/editor.js
elements/jsonform/test/cases/trigger-change-event.js
elements/storytelling/src/components/editor.js
elements/storytelling/src/helpers/editor.js
elements/storytelling/test/cases/load-editor.js
package-lock.json

- Replaced simpleMDE with easyMDE in StoryTelling 
- Improved styling of easyMDE based on old editor design  
- All async and setTimeout are still required

Fix: Replaced simplemde editor with easymde on StoryTelling

---

elements/storytelling/src/helpers/editor.js

In https://github.com/EOX-A/EOxElements/actions/runs/9175391835/job/25229841043 we noticed the `markdown-with-editor` story had an error (`> Cannot read properties of null (reading 'addEventListener')`).
This PR adds a conditional to the querySelector so that the event listener is only added if `.CodeMirror-scroll` is available

fix: wheel event listener error when querySelector is null

---

elements/jsonform/src/style.eox.js
elements/storytelling/CHANGELOG.md

- Small styling issue when the value of range goes double or more. 
From > To

Fix: Styling stacking issue when range value become bigger

---

elements/geosearch/src/main.js
elements/geosearch/src/style.eox.js
elements/geosearch/src/style.js

* Fix the pointer overlay issues found in the original merged version of the EOxGeoSearch (the map would not be interactive behind the search results which were only hidden visually and not semantically).
* Do not execute any API calls if the query string is smaller than two characters, as a 400 would be coming back for these.
* Show a textual indicator in place of the results when the query string is too short.

fix: implement a number of usability improvements for the geosearch element

---

elements/map/main.ts
elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/stories/index.js
elements/storytelling/stories/markdown-init-event.js
elements/storytelling/stories/storytelling.stories.js

Introducing `@init` event to update the elements when markdown is initialised or changed. 
```vue
<eox-storytelling
markdown="## Welcome to the story editor "
@init=${({ detail }) => {
if (detail?.tagName === "EOX-MAP") {
detail.registerProjection(
"EPSG:3035",
PROJDICT["EPSG:3035"].def
);
}
}}
></eox-storytelling>
```

Feat: The widget hook initialize based on the @init event 

---

elements/layercontrol/src/methods/layer/input-click.js
elements/layercontrol/test/cases/general/exclusive-layers.js
elements/layercontrol/test/cases/general/index.js
elements/layercontrol/test/general.cy.js

This includes layer groups in the exclusive layer visibility check; it allows to mix layers and groups and have all of them exclusive (by setting teh `layerControlExclusive` property).

fix: add support for exclusive groups

---

elements/map/src/generate.ts

This PR changes the order of spreading the formats, layers and sources from the "advanced" plugin to happen first, and then the basic ones afterwards, as there were some issues that the internal ones were modified but then overwritten by the plugin ones.

fix: order of format, layer and source spread

---

elements/map/map.stories.js
elements/map/src/generate.ts
elements/map/src/tileGrid.ts
elements/map/test/fixtures/eoxCapabilities.xml
elements/map/test/wmts.cy.ts

This PR brings the possibility to defined tile grids for WMTS sources as well as projections for sources, which could be relevant in this context.
To keep it simple, WMTS tile grid generation has been simplified to the bare minimum. Resolutions are created for all zoom levels, extent has to be defined on the layer level. XYZ tilegrid generation remains unchanged.
For now, this has only been tested for 3857 data, though other projections should work, as long as the projection is registered on the map.

Feat: WMTS Tile Grid & Source Projections

---

.github/workflows/dev-release.yml

Created a dev release github action that can be triggered manually and takes an input of the branch name to be deployed and an optional postfix of the released version that defaults to `dev`. This implementation has not been tested yet; [the workflow must be in default branch of the repo to be triggered](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatch).
Related to #530.

Chore: Create dev release action

---

elements/map/main.ts
elements/map/src/select.ts
elements/map/test/hoverInteraction.cy.ts

This PR handles the issue described in  #587. The idea is that sorting the ol layers by removing and re-adding them will not actually remove the connected interactions.
@silvester-pari is this how the desired behaviour?

Fix: unmanaged Styles

---

elements/map/src/compare.ts

This PR fixes the height of the comparison container, so it only takes up the space of the map(s).

fix: height of compare container

---

elements/map/map.stories.js
elements/map/src/compare.ts
elements/map/test/compare.cy.ts

This PR adds a new functionality to the `eox-map-compare` and allows to toggle the comparison mode via the new `enabled` attribute:
- `enabled="first"` only shows the first map
- `enabled="second"` only shows the second map
- `enabled` (`undefined` or any other truthy value; default) shows both maps
This effectively allows enabling/disabling the comparison in a flexible way.

feat: enable/disable compare

---

.github/workflows/dev-release.yml

automatically adding a  time stamp to  every dev release preid

fix: add timestamp to preid

---

elements/map/main.ts
elements/map/test/sync.cy.ts
elements/map/tsconfig.json
utils/getElement.js
utils/index.js

This PR adds the functionality to pass an `eox-map` directly to the `sync` property. Previously it only took a `string` and internally did a `document.querySelector`, but if the `eox-map` is used within another shadow root, then this query selector didn't work.
Now there are two options:
- pass a `string` as attribute or property, e.g. `<eox-map sync="#other-map">`
- pass a DOM element as property, e.g. `eoxMapB.sync = document.querySelector("#other-map")`

feat: allow passing an eox-map DOM element to `sync` property

---

package-lock.json
package.json

Pins the required Node version  to current LTS (`20.15.1`)

chore: pin node version to current LTS (20.15.1)

---

elements/layercontrol/src/main.js
elements/layercontrol/src/methods/layercontrol/first-update.js

Enables the Layer Control to take both string selectors and HTML elements in its `for` attribute thanks to Silvester's new `getElement` function.

feat: allow passing an eox-map DOM element to `for` property 

---

elements/itemfilter/src/components/filters/selector.js
elements/itemfilter/src/enums/config.js
elements/itemfilter/src/main.js
elements/itemfilter/src/methods/results/create.js
elements/itemfilter/src/style.eox.js
elements/itemfilter/stories/primary.js
elements/itemfilter/test/cases/general/external-filter.js
elements/itemfilter/test/cases/general/index.js
elements/itemfilter/test/cases/general/subtitle.js
elements/itemfilter/test/cases/state/result-pre-checked.js
elements/itemfilter/test/general.cy.js
elements/itemfilter/test/state.cy.js

This PR introduces a new style for result lists:

feat: improved list style

---

elements/map/src/generate.ts
elements/map/test/groupLayer.cy.ts

This PR fixes a bug when updating layers inside layer groups.
Additionally, this PR adds another test to more realistically simulate real-world situations when working with groups. This test also detects failing `instanceof`-checks that occured in the past when multiple instances of `ol` are installed in the project.
connected to https://github.com/EOX-A/EOxElements/issues/975

fix: layer update of group layers

---

elements/timecontrol/src/main.js
elements/timecontrol/stories/index.js
elements/timecontrol/stories/no-map.js
elements/timecontrol/stories/timecontrol.stories.js

This enables the timecontrol to have no map associated to it and fixes the issue of multiple events being triggered when the slider is displayed.

Fix: enable timecontrol to have no map

---

elements/map/src/generate.ts

This PR attempts once more to fix the layer group update by creating a shallow copy before iteration, so that removing an item from the original array doesn't affect the logic negatively.

fix: issue of layer groups not removing all previous layers

---

elements/storytelling/src/main.js

- missing `.markdown` property was causing the markdown to reset every time any user closes the editor.

Fix: Closing editor was causing markdown getting reset

---

elements/itemfilter/src/style.eox.js

This PR fixes the highlighting on hover for the result items and adds a visually more prominent highlighting for selected items (introducing a new CSS variable called `--item-select-color`).
[Screencast from 2024-08-05 11:38:00.webm](https://github.com/user-attachments/assets/0e5b76f8-d975-4ac5-9075-fffabc742dcc)

fix(style): highlight on hover and primary color on select

---

elements/map/map.stories.js
elements/map/src/select.ts
elements/map/test/selectInteraction.cy.ts

This PR implements animations for programmatic feature selection for both VectorLayer and VectorTileLayer without causing a version jump of the map element.
The internally used `panIntoFeature` function has been lifted to the level of the interaction, exposing it the same way as the `highlightById` function as a method of the interaction itself.
The existing `highlightById`-method now has an optional second parameter, `fitOptions`, allowing animations to highlighted Features of `VectorLayer` and RenderFeatures of a `VectorTileLayer`. Be aware that when programmatically selecting a feature, the source has to be loaded, and, in the case of the `VectorTileLayer`, the feature has to be available in currently rendered tiles. The [`fitOptions`](https://openlayers.org/en/latest/apidoc/module-ol_V …

feat: highlight and animate feature(s) by ID

---

elements/map/main.ts
elements/map/map.stories.js
elements/map/src/utils.ts
elements/map/test/viewProjection.cy.ts

This PR adds the read-only-properties `EOxMap.lonLatCenter` and `EOxMap.lonLatExtent`, which return the current center and extent in EPSG:4326, no matter the current projection of the view. 
Additionally, the new methods `transform` and `transformExtent` are now exposed, allowing more flexible transformations between all registered coordinate systems. Basically, these methods are the `ol/proj` [transform](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transform) and [transformExtent](https://openlayers.org/en/latest/apidoc/module-ol_proj.html#.transformExtent) functions, with the small adaptation that the `destination` defaults to `EPSG:4326` if not defined.

feat: lonLatCenter & lonLatExtent

---

elements/geosearch/src/main.js
elements/geosearch/stories/custom-loader.js
elements/geosearch/stories/geosearch.stories.js
elements/geosearch/stories/index.js

Integrates the recently implemented standard map loading indicator into the geosearch element, with an option to customize the SVG loader using the `loaderSvg` attribute, as demonstrated in the new Custom Loader story.
Do you, @silvester-pari think maybe we should centralize the loader/spinner SVG, similar to how we handled the styles for buttons, radio buttons and checkboxes? Also I think maybe a blue would fit better with the rest, instead of orange.

feat: implement loading indicator

---

elements/map/helpers.ts
elements/map/test/viewProjection.cy.ts

This PR adds `extent` as an optional third parameter to the `registerProjection` function. This allows setting the validity extent for the set projection. Details see [the corresponding OL docs](https://openlayers.org/en/latest/apidoc/module-ol_proj_Projection-Projection.html#setExtent).

feat: added optional extent for the registerProjection function

---

elements/timecontrol/src/sliderticks.js

Closes #1165.
Calculate slider ticks lazily as a method instead of providing a reactive getter, improving initial load performance 10-fold.
| No. of  Test Entries | Previous (eager) start-up time | Current (lazy) start-up time|
|---	|---	|---   	|
|2277   |9.8s   	|760ms   	|

fix: pre-calculate slider ticks to reduce loading time

---

elements/storytelling/src/helpers/validator.js

- Array validation was not included inside the Group's layer validator.  Updated validator code as per `array`

Fix: Update layers group validation

---

elements/map/test/viewProjection.cy.ts

Some tests (e.g. `map/viewProjection`) have assertions that fail after the test has ended.
In the above screenshot, the `lonLatExtent` assertion is actually part of "use special projection" test but because of a `setTimeout` it gets pushed down to the next test.
In order to fix this we wrap the assertion in a `Cypress.Promise` (https://docs.cypress.io/api/utilities/promise) as we do in other tests that require a `setTimeout` and as a result the test now fails which needs fixing on the map side.

chore: fix flaky tests

---

elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js

- Disable individual title from nav bar using `nav: false` config like - 
```md
```
https://github.com/user-attachments/assets/3e659273-8098-4645-927e-8f069ce72708

Feat: disable individual title from nav 

---

elements/timecontrol/src/main.js
elements/timecontrol/src/style.eox.js

* selected time label is now between previous/next buttons
* added text-center style to main to center component to where they are integrated (slider is not width reactive)
* buttons and label have their own div container to be on same row
Now:
Previous:

feat: changed style 

---

elements/timecontrol/src/main.js
elements/timecontrol/src/sliderticks.js

Time Control slider ticks tend to get out of alignment as the size of the date array grows larger. This becomes an issue especially with datasets that span multiple decades, as some datasets easily go from 1960 to 2024.
This PR implements a high-density mode which condenses individual ticks into bars automatically if the density of slider ticks gets too high. Furthermore, the last unnecessary getter/setter has been removed inside the ticks to yield a bit better performance with large datasets (20-25k entries).

feat: decade ticks

---

elements/layout/src/enums/index.js
elements/layout/src/enums/stories.js
elements/layout/src/main.js
elements/layout/stories/gap.js
elements/layout/stories/grid.js
elements/layout/stories/primary.js

Removes default styling for eox-layout since we anyways tend to override it for each use. The style has instead been added to the storybook stories.
Closes #1110

fix: remove default style

---

elements/layercontrol/src/components/layer-list.js
elements/layercontrol/src/components/layer-tools.js
elements/layercontrol/src/main.js

This PR brings the same "treatment" to the layercontrol like previously for the itemfilter in #1280.

fix(style): introduce padding variable

---

elements/itemfilter/src/style.eox.js

This fixes a small issue with non-aggregated lists, following the previous PR that introduced paddings

fix(style): adapt padding for non-aggregated lists

---

elements/itemfilter/src/components/expand-container.js
elements/itemfilter/src/style.eox.js

This PR introduces a new CSS variable called `text-transform`. With this, the default text-transform of filter property titles, filter properties and results can be overridden (default is `capitalize`).

feat(style): add text-transform variable

---

elements/map/src/helpers/generate.js
elements/map/test/cases/group-layer/index.js
elements/map/test/cases/group-layer/keeps-layer-order-inside-group.js
elements/map/test/groupLayer.cy.js

This PR fixes a problem described in #1251 about the stability of nested layers. The problem was a faulty conversion from the reverse-painter-order of the `EOxMap` layer json notation to the painter-order of `ol`.
The problem was quite hidden because it only affected the layer order inside group layers and only occured when `updating` the layers. A simple test has been added that sets the same layer json to a map, which actually reversed the layer order in `ol` until now.

fix: layer order stability insided group layers

---

elements/itemfilter/src/helpers/chip-items.js

Turns out the issue described in #1325 was a generic issue that didn't render any chip title if no filter `title` is provided. This PR introduces a fallback to use the `key` if no `title` is provided.

fix: fall back to filter key if no title is provided (chip display)

---

elements/map/src/helpers/select.js

This PR removes the hardcoded `setActive(true)` in the change listener for `selectLayer`. This caused issues if the selection was currently set to `active = false` and updating the layer would mistakenly reset the interaction back to `active`.

fix: keep `selectLayer` activation state in change listener

---

elements/drawtools/src/main.js
elements/drawtools/src/methods/draw/init-layer.js

This initializes the draw layer with a `zIndex` of 100, so that it is on top of other layers in the majority of cases.

fix: initialize draw layer with `zIndex` 100

---

elements/map/src/helpers/select.js
elements/map/test/cases/select/add-select-interaction-vector-tile.js
elements/map/types.ts

This PR adds a `pointer` cursor in situations where we have a "click" select interaction.
It also adds two more options for the interaction:
- `cursor`: the desired cursor if the mouse hovers over a feature
- `atPixelOptions`: the native [ol `atPixelOptions` object](https://openlayers.org/en/latest/apidoc/module-ol_Map.html) allowing to set things like `hitTolerance` or `checkWrapped`.
This is an alternative implementation to #1342.
[Screencast from 2024-10-29 11:29:18.webm](https://github.com/user-attachments/assets/bc53c512-9057-4a61-a020-f6f7abc6634b)

feat: add hover interaction pointer cursor (alternative)

---

elements/map/src/helpers/generate.js
elements/map/src/helpers/select.js
elements/map/src/main.js
elements/map/src/methods/map/remove.js
elements/map/test/cases/select/index.js
elements/map/test/cases/select/remove-select-interaction-layer.js
elements/map/test/selectInteraction.cy.js

This PR fixes a bug with removing the select interaction when updating the layer. Also, there was still an .only on the select-interaction tests from the refactoring, causing test cases to be disabled.
Originating from commits in https://github.com/EOX-A/EOxElements/pull/1342.

fix: properly remove interaction on layer update

---

elements/storytelling/src/components/editor.js
elements/storytelling/src/helpers/editor.js
elements/storytelling/src/main.js
package-lock.json

- Implemented - @change event when markdown is changed and let the parent access the triggered event `detail`
- Disable `auto-save` for `git-clerk` because we will be using `json-editor` of `git-clerk`

feat: event update for markdown change and disable-autosave option

---

elements/itemfilter/src/enums/config.js
elements/itemfilter/src/main.js
elements/itemfilter/src/methods/results/create.js
elements/itemfilter/src/style.eox.js
elements/itemfilter/stories/card-display.js
elements/itemfilter/test/cases/general/image.js
elements/itemfilter/test/cases/general/index.js
elements/itemfilter/test/general.cy.js
elements/itemfilter/test/testItems.json

This PR introduces an `imageProperty` property, which allows (similarly to `titleProperty` and `subTitleProperty`) to define a property to render as image, both in "cards" and "list" mode.

feat: display result image with ` imageProperty`

---

elements/drawtools/src/helpers/features-to-geojson.js
elements/drawtools/src/helpers/features-to-wkt.js
elements/drawtools/src/helpers/index.js
elements/drawtools/src/main.js
elements/drawtools/src/methods/draw/emit-drawn-features.js
elements/drawtools/stories/drawtools.stories.js
elements/drawtools/stories/formats.js
elements/drawtools/stories/index.js
elements/drawtools/test/cases/index.js
elements/drawtools/test/cases/set-different-formats.js
elements/drawtools/test/general.cy.js

Related to #1276, This Introduces a new attribute `format` to the drawtools, that determines the emitted format of the drawn features.

feat: support emitting the drawn features in `WKT` and `GeoJson` formats

---

elements/layercontrol/src/components/layer.js
elements/layercontrol/stories/index.js
elements/layercontrol/stories/layer-color.js
elements/layercontrol/stories/layercontrol.stories.js
elements/layercontrol/test/cases/general/color-swatch.js
elements/layercontrol/test/cases/general/index.js
elements/layercontrol/test/general.cy.js

To make it easier to associate layers with additional information in a parent app, this pull requests implements color swatches for individual layers. These automatically replace the icons of layers and layer groups with the color swatch as long as the `color` attribute is set in the OpenLayers layer.

feat: color swatches for layers and layer groups

---

elements/itemfilter/src/methods/results/create.js

This fixes a small bug where the image container was only rendered if there was a subtitle present.

fix: correctly render title-container also if no subtitle present

---

elements/drawtools/src/main.js

This PR fixes the removal of the `eox-drawtools` element - when disconnecting, it makes sure to also remove the automatically created `drawLayer`.

fix: Remove the drawLayer when the element is disconnected

---

utils/styles/main.css

This PR introduces a small fix that enables `overflow: auto` for code blocks. Previously the content was overflowing.

fix(style): use auto overflow for pre/code blocks

---

elements/itemfilter/src/methods/results/create.js

This PR adds a small fix that lets the user click the entire result list item instead of just the title.
[Screencast from 2024-12-09 16:39:23.webm](https://github.com/user-attachments/assets/88550785-a151-4f18-823e-0f431cb3ecfa)

fix: listen for click on entire result instead of just title

---

elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/style.eox.js

- Added navigation for mobile view 
- Added hamburger menu to control navigation list 
- Navigation list pops from bottom 
https://github.com/user-attachments/assets/28533366-f779-472a-aad0-697e084fb8c6

Fix: Storytelling navigation in mobile view

---

elements/map/src/helpers/select.js
elements/map/test/cases/hover/disable-tooltip.js
elements/map/test/cases/hover/index.js
elements/map/test/tooltip.cy.js
elements/map/types.ts

This PR adds the feature of disabling the `tooltip` part of the `select` interaction by setting `options.tooltip = false`, as discussed in #1358

feat: disable tooltip of select interaction

---

elements/timecontrol/src/main.js
elements/timecontrol/stories/format.js
elements/timecontrol/stories/index.js
elements/timecontrol/stories/timecontrol.stories.js
elements/timecontrol/test/cases/index.js
elements/timecontrol/test/cases/load-date-format.js
elements/timecontrol/test/general.cy.js

- Added `format` attribute inside `<eox-timecontrol>` to format Date and Time using `dayjs` [format](https://day.js.org/docs/en/display/format).
```html
<eox-timecontrol
.format="MMMM DD, YYYY"
></eox-timecontrol>
```

feat: date/time display format

---

elements/layercontrol/src/components/layer-tools.js
elements/layercontrol/src/components/tools-items.js

This PR improves the rendering of the layer tools in list display:
- moved icon to the left instead of right
- added tool title
- adjusted paddings/margins
- removed white background

feat(style): improve rendering of layer tools list display

---

elements/timecontrol/src/main.js
elements/timecontrol/src/style.eox.js
elements/timecontrol/stories/disabled-play-button.js
elements/timecontrol/stories/primary.js
elements/timecontrol/stories/programmatic-time-selection.js
elements/timecontrol/stories/slider.js

This PR introduces
- fixes for button styling, alignment, padding
- introduction of a css variable `--navigation-button-display`, if set to `none`the left/right buttons are hidden

feat(style): adjust button styling, paddings, add css variable

---

elements/map/src/helpers/select.js
elements/map/test/cases/select/add-select-interaction-to-existing-layer.js
elements/map/test/cases/select/index.js
elements/map/test/selectInteraction.cy.js

This PR fixes an issue described in #1404, where the cursor did not change correctly when the interaction was added by updating an existing layer.
The issue was that in https://github.com/EOX-A/EOxElements/pull/1348 the interactions were taken from the properties of the `ol`-layer directly instead of the `_jsonDefinition` or the `interactions` or the `eoxMap`.
A test was added to test both the cursor as well as the select-interaction itself if the interaction was added after a delay.

fix: cursor-change after layer-interaction update

---

elements/layercontrol/src/components/layer-legend.js
elements/layercontrol/src/components/layer-tools.js

This PR adds two small fixes to limit the width of images and legends inside layercontrol:
- in the `info` tool, the `max-width` was limited to `100%`
- in the layer legend, the width was taken from the elements `offsetWidth` and applied (additional render requested)

fix(style): prevent legend and info overflow

---

elements/itemfilter/src/methods/results/create.js

This PR adds a very simple fallback (svg box with primary color) if some of the results don't have an image set.

feat: fallback for not-existing result images

---

elements/layercontrol/src/components/layer-datetime.js
elements/layercontrol/src/enums/stories/index.js

This allows passing the `displayFormat` property in `layerLegend`, so the newly introduced functionality of changing the display format can be used.

feat: pass displayFormat property to timecontrol

---

elements/jsonform/src/style.eox.js
elements/layercontrol/src/components/layer-group.js
elements/layercontrol/src/components/layer-list.js
elements/layercontrol/src/components/layer.js
elements/layercontrol/src/components/tools-items.js
elements/layercontrol/src/main.js

This PR introduces two new CSS variables to better control the layout:
-  `--layer-summary-visibility`: controls the layer group summary (for e.g. hiding the dropdown arrow)
-  `--padding-vertical`: vertical padding, similar to previously added horizontal padding

fix(style): summary & spacing CSS variables

---

elements/layercontrol/src/components/layer-datetime.js
elements/timecontrol/src/main.js

This PR introduces a navigation property to enable/disable navigation buttons.

feat: time control navigation property

---

elements/layercontrol/src/components/layer-datetime.js
elements/layercontrol/src/enums/stories/index.js
elements/layercontrol/stories/layercontrol.stories.js
elements/timecontrol/src/enums/stories.js
elements/timecontrol/src/main.js
elements/timecontrol/stories/disabled-buttons.js
elements/timecontrol/stories/format.js
elements/timecontrol/stories/index.js
elements/timecontrol/stories/no-map.js
elements/timecontrol/stories/primary.js
elements/timecontrol/stories/programmatic-time-selection.js
elements/timecontrol/stories/slider.js
elements/timecontrol/stories/timecontrol.stories.js

This PR changes the `disablePlay` property into a `play` property to better align it with other properties such as `slider` and `navigation`. The default value is `false`.
This is a breaking change - make sure to also invert the logic (first `disablePlay: true` now becomes `play: false`etc.)!

fix!: align play button property with others (`disablePlay`-> `play`)

---

elements/jsonform/src/style.eox.js
elements/layercontrol/src/components/layer-tools.js

Fixes alignment of `info-content` slot in `eox-layercontrol` and hardcoded background in `eox-jsonform`'s `select`

chore: fix hardcoded background color in jsonform

---

elements/jsonform/src/style.eox.js

Force output to have fixed with so slider isn't shaky
Before
After

fix: range-control output fixed width

---

elements/storytelling/src/helpers/render-html-string.js

- Fixed two senario: 
- When there is no content in storytelling editor and it shows (+) button
- When there is content without section tag (##), then error is removed
https://github.com/user-attachments/assets/0e3620c0-4f96-4538-afdd-88e472c7d804

Fix: Adding content without any sections breaks editor

---

elements/storytelling/src/helpers/render-html-string.js

When uploading media using the GitHub API in [git-clerk](https://github.com/EOX-A/git-clerk), we can only use its permanent URL. This ensures the media is always accessible, even if the branch is merged or deleted. However, the permanent URL becomes available to users only after a delay of one minute.
- Utilize the commit URL as a fallback src. While the commit URL is not suitable for permanent purposes, it is available immediately after merging. This allows the image to be loaded into storytelling until the permanent URL is ready. (This ensures users can view the image without delay.)
- To achieve this, we use the attribute `data-fallback-src=""` property to load the backup URL, as shown below:
```md
```
- If any normal image don't load a default `fallback-src` will be loaded - …

fix: fallback for media src

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/stories/index.js
elements/jsonform/stories/jsonform.stories.js
elements/jsonform/stories/validation.js
elements/jsonform/test/cases/index.js
elements/jsonform/test/cases/submit-button.js
elements/jsonform/test/general.cy.js

This PR adds a default callback for an `onSubmit` function, which just emits the `submit` event on the `eox-jsonform` element.
`json-editor` supports [defining a button on the form](https://github.com/json-editor/json-editor?tab=readme-ov-file#button-editor), which only is clickable once validation passes, e.g.:
```js
button: {
format: "button",
options: {
button: {
text: "Submit",
action: "onSubmit",
validated: true,
},
},
},
```
In order to do something on click, an `onSubmit` callback must be registered before initializing the JSONEditor. In order to support a generic "submit" functionality, a `onSubmit` callback was registered, which dispatches a custom `submit` event, so that it can be listened e.g.:
```html
<eox-jsonform
@submit=${(e) => alert(`Submitted: …
```

feat: submit button callback

---

elements/map/src/methods/map/setters.js

This adds a small fix when syncing two views: for some reason, when syncing two views and the "receiving" one is not visible (and thus its view is not initially visible and usually defaults to 0 zoom if nothing else is defined), it "forces" its zoom onto the "giving" one (if no explicit zoom is set there as well). To mitigate this, when the "receiving" one is hidden **and** the "giving" one has no zoom set, it syncs the "other way round" in order for this zoom reset not to happen.

fix: view sync between a visible and a hidden view

---

elements/jsonform/package.json
elements/jsonform/src/main.js
package-lock.json

This PR adds the functionality to use (sanitized) HTML in titles, descriptions etc. This is achieved by adding a DOM sanitizer (see https://github.com/json-editor/json-editor/blob/cb10e1cc2ca3d3be57e4e51827e6f2de74f76fe4/UPGRADING.md#option-description).

feat: allow HTML in titles and descriptions

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/src/style.eox.js
elements/jsonform/stories/jsonform.stories.js

This PR adds another property on the `form` element (`[data-theme-custom="eox"]`) to ensure the overriden styles are actually overridden. There were some issues that styles bundled in jsonform were loaded in a different order, causing style glitches.
In the future, we should probably create a proper custom theme and not base it on the `html` theme.

fix: ensure custom theme overrides are applied

---

elements/jsonform/package.json
elements/jsonform/src/helpers/editor.js
elements/jsonform/src/style.eox.js
elements/jsonform/stories/code.js
elements/jsonform/stories/index.js
elements/jsonform/stories/jsonform.stories.js
elements/jsonform/stories/public/codeSchema.json
elements/jsonform/test/cases/index.js
elements/jsonform/test/cases/load-code.js
elements/jsonform/test/general.cy.js
package-lock.json

This PR adds support for code editors powered by Ace. See the information about the json-editor integration [here](https://github.com/json-editor/json-editor/tree/master?tab=readme-ov-file#specialized-string-editors).
Passing the [configuration options](https://github.com/sparksuite/simplemde-markdown-editor#configuration) (including [themes](https://github.com/ajaxorg/ace/tree/master/src/theme)) to `options.ace` in the schema can modify behavior and appearance of the editor.

feat: add support for code editor

---

elements/stacinfo/src/helpers/properties.js

This PR checks if the rendered links are part of the `providers` object, and if so, disables the `roles === metadata` check.

fix: allow provider roles when filtering out links

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/src/style.eox.js

Workaround to hide tabs where `options.hidden` is set on a property. See https://github.com/json-editor/json-editor/issues/1577

fix: hide category tabs where property has `options.hidden`

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/stories/feature-selection.js
elements/jsonform/stories/geojson.js
elements/jsonform/stories/jsonform.stories.js
elements/jsonform/stories/primary.js
elements/jsonform/stories/public/basicSchema.json
elements/jsonform/stories/validation.js
elements/jsonform/stories/wkt.js
elements/jsonform/test/cases/trigger-change-event.js

This PR adds a workaround to emit a `change` event for string type input fields (`input` event). This makes the text input behavior harmonized with all the other inputs.

fix: trigger `change` event on text inputs

---

elements/jsonform/src/helpers/editor.js

- Repeated child creation occurs inside `eox-jsonform` because the child is not removed from the form when generating a new form.
https://github.com/user-attachments/assets/7ba6230d-be09-4501-a569-c5f345f26ad6

Fix: Repeated form child creation on jsonform

---

elements/jsonform/src/style.eox.js

This PR removes the bottom margin of the last rows and last form controls in order to not set unnecessary bottom margin if not needed. It also sets the eox-jsonform to `display: block` and `overflow:hidden` by default, which allows more versatility and less repeated setup needed for usage in applications.

fix(style): remove last row margin and prevent form overflow

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/src/main.js
elements/jsonform/test/cases/index.js
elements/jsonform/test/cases/load-optional-fields.js
elements/jsonform/test/general.cy.js

This PR ensures optional fields are always shown, even if a `value` has been passed to the editor. By default, json-editor hides optional fields as soon as a value is set 8see linked discussion in the code comment), but we mitigate this by setting `show_opt_in` to true and then both clicking the resulting checkbox and at the same time removes it, in order to make lives easier for users filling out the form.

fix: always show optional values

---

elements/drawtools/src/main.js
elements/drawtools/src/methods/draw/on-draw-end.js
elements/drawtools/stories/continuous-drawing.js
elements/drawtools/stories/drawtools.stories.js
elements/drawtools/stories/index.js

introduced `continuous` attribute. when `continuous` is set to true the user can select/draw continuously without discarding or removing the old feature. related to eodash/eodash#171
https://github.com/user-attachments/assets/29f13b89-8e2d-4e5c-ae89-efcdf060e99c

Feat: Introduce continuous drawing

---

elements/storytelling/src/helpers/editor.js
elements/storytelling/src/style.eox.js

This PR fixes the broken overflow introduced to scrollytelling element and the editor by the recent jsonform updates.

fix(style): overflow on storytelling and editor

---

elements/drawtools/src/components/list.js
elements/drawtools/src/main.js
elements/drawtools/stories/multi-feature-select.js
elements/drawtools/stories/multi-polygon-list.js

This PR introduces a `featureName` property that can be used to set the name of features in the rendered list (before it was hardcoded to "Feature").

feat: allow setting feature name for rendered list

---

elements/drawtools/src/components/list.js
elements/drawtools/src/enums/test.js
elements/drawtools/src/methods/draw/init-layer.js
elements/drawtools/src/methods/list/delete-feature.js
elements/drawtools/src/methods/list/first-update.js
elements/drawtools/test/_mockMap.js
elements/drawtools/test/cases/feature-list.js
elements/drawtools/test/cases/index.js
elements/drawtools/test/general.cy.js

This fixes feature deletion in the rendered feature list. It was probably broken in a previous change where the export format was changed.
In addition, it adds a new test regarding the feature list, which required actually using real ol Features, since mocking wasn't feasible.

fix: feature deletion by index

---

elements/jsonform/src/main.js
elements/jsonform/stories/external.js
elements/jsonform/stories/jsonform.stories.js

This PR forwards the editor "ready" event. This event fires once the editor has finished loading the (remote) schema and has built the form, and thus the internal editor API is ready to be used.
In the past, we emitted the "ready" and "change" event all as "change", which made it hard to distinguish between a real "change" event and the "ready" event.
This now allows such things as
```js
const jsonForm = document.querySelector("eox-jsonform");
jsonForm.addEventListener("ready", () => {
// Now the api methods will be available
jsonForm.editor.validate();
});
```

feat: forward editor ready event

---

elements/drawtools/src/methods/draw/on-draw-end.js

This stops holding on to discarded features internally when drawing continuously. Close #1572;

fix: discard features cleanly on continuous drawing

---

elements/jsonform/src/helpers/editor.js

This PR makes use of the dynamic import functionality in ace editor (for modes, themes etc.) in order to reduce the amount of output bundle files. This brings the number of files in the dist folder from 478 back down to 2.
Fixes #1588.

fix: use dynamic imports to reduce bundle

---

elements/jsonform/src/enums/editor.js
elements/jsonform/src/enums/index.js
elements/jsonform/src/helpers/editor.js

This PR provides a default fallback schema if no `schema` property has been passed. This was causing an error since the `schema.properties` were not found by the json-editor schema resolver.

fix: provide fallback schema if no schema provided

---

elements/jsonform/src/helpers/editor.js

This PR adds support for recursive "hidden" properties. When providing the `"format": "categories"` functionality in https://github.com/EOX-A/EOxElements/pull/1532, this was only implemented for the root level, whereas now it works also for nested properties.

fix: recursively hide hidden property tabs

---

elements/drawtools/test/_mockMap.js
elements/map/src/controls/controls.js
elements/map/src/controls/geo-location.js
elements/map/src/controls/loading-indicator.js
elements/map/src/custom/sources/FlatGeoBuf.js
elements/map/src/custom/sources/WMTSCapabilities.js
elements/map/src/helpers/add-new-feature.js
elements/map/src/helpers/generate.js
elements/map/src/helpers/interactions.js
elements/map/src/helpers/select.js
elements/map/src/methods/map/setters.js
elements/map/src/plugins/advancedLayersAndSources/formats.js
elements/map/src/plugins/advancedLayersAndSources/layers.js
elements/map/src/plugins/advancedLayersAndSources/sources.js
elements/map/test/utils/events.js

This PR removes the usage of "barrel files" (#1527), as they can be negative towards bundle size and will be removed in `ol` at some point in the future. The removal has been done using https://www.npmjs.com/package/@openlayers/codemod and manually fixing passages where the codemod failed, like when we access classes from a barrel file using the bracket notation (e.g. `sources[sourceType]`).

chore: remove barrel files

---

elements/stacinfo/package.json
package-lock.json

Downgrades and fixes stac-fields to `v1.5.2` in order to fix Storybook rendering (see https://github.com/stac-utils/stac-fields/issues/32)

chore: downgrade stac-fields

---

elements/stacinfo/package.json
package-lock.json

This undos https://github.com/EOX-A/EOxElements/pull/1612 after a fix update by `stac-fields` (see https://github.com/stac-utils/stac-fields/pull/33).

chore(deps): update stac-fields version

---

elements/storytelling/package.json
elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/src/style.eox.js
elements/storytelling/stories/markdown-editor.js
package-lock.json

This PR adds footnote support in md using `markdown-it-footnote`.
```md
Specifically, **scrolly**telling[^1] adds another layer of engagement, which allows the user to interact with the website by simply scrolling through it.
[^1]: Blend of *scroll* + *storytelling*. [Storytelling enriched with multimedial elements triggered while scrolling down a webpage](https://en.wiktionary.org/wiki/scrollytelling).
```

feat: add md footnote support

---

elements/layout/src/main.js
elements/layout/stories/index.js
elements/layout/stories/layout.stories.js
elements/layout/stories/scroll.js

This PR adds the attributes `row-height` and `column-width` to the parent layout element. This allows setting a fixed dimension; note that if the total height/width is larger than the parents height/width, overflow scrolling is automatically enabled.

feat: support fixed row height/column widths

---

elements/storytelling/src/style.eox.js
elements/storytelling/stories/markdown-editor.js

This fixes an issue introduced by https://github.com/EOX-A/EOxElements/pull/1476, where the styling of the section (full scren image, etc.) was also wrongly applied to the content inside tour steps.

fix: prevent applying section styling to steps

---

elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/style.eox.js

- Initialize the element value of the tour at the beginning when a section is visible at  intersection observer  
https://github.com/user-attachments/assets/0e3d2555-91ae-4834-b009-4fc9e0f52672

Fix: Initialize tour elements after section loaded

---

elements/layout/src/main.js
elements/layout/stories/fill-grid.js
elements/layout/stories/index.js
elements/layout/stories/layout.stories.js

By adding the `fill-grid` attribute to `eox-layout`, the individual items fill the available space without gaps. The `w` and `h` attributes on items can be used to determine the relative width/height, whereas the  `row-height` and `column-width` attributes on the layout determine the minimum height/width of the grid items.
https://github.com/user-attachments/assets/4ffa88b0-0888-4469-a598-82cb11088cc3

feat: fill-grid mode

---

elements/layout/src/main.js
elements/layout/stories/index.js
elements/layout/stories/layout.stories.js
elements/layout/stories/responsive.js

This PR adds support for different screen sizes. By default, the breakpoints are `[0, 600, 1280]` (pixels) and each layout item can have 3 values (e.g. `w="2/4/6"`). This way, completely different layouts for different screen sizes can be created.
https://github.com/user-attachments/assets/c5a78c87-b4e2-4771-97a9-dcb68a23da94

feat: responsive layout (s/m/l)

---

elements/itemfilter/package.json
elements/itemfilter/src/components/results.js
elements/itemfilter/src/methods/results/create.js
elements/itemfilter/src/style.eox.js
elements/itemfilter/stories/card-display.js
package-lock.json

This PR introduces `eox-layout` for rendering the itemfilter result cards. It has a default max/min height/with of 300x200 for the cards and a 16px gap, and a border radius of 8px, which is configurable via CSS vars on `eox-itemfilter`:
- `--card-width`
- `--card-height`
- `--card-gap`
- `--card-border-radius`
https://github.com/user-attachments/assets/f8ac7a1f-c09c-4ed8-b769-d8a3379eed19

feat(style): replace result cards with eox-layout

---

.release-please-manifest.json
.storybook/preview.js
README.md
elements/feedback/README.md
elements/feedback/package.json
elements/feedback/src/css.d.ts
elements/feedback/src/enums/index.js
elements/feedback/src/enums/test.js
elements/feedback/src/feedback-button.js
elements/feedback/src/main.js
elements/feedback/src/style.eox.js
elements/feedback/src/style.js
elements/feedback/stories/button.js
elements/feedback/stories/feedback.stories.js
elements/feedback/stories/index.js
elements/feedback/stories/primary.js
elements/feedback/test/cases/click-button.js
elements/feedback/test/cases/index.js
elements/feedback/test/cases/load-feedback.js
elements/feedback/test/general.cy.js
elements/feedback/tsconfig.build.json
elements/feedback/vite.config.js
package-lock.json
package.json
release-please-config.json
tsconfig.json

This PR introduces the new `eox-feedback` element, an easy way to provide feedback in UIs. It does a POST request to a provided server endpoint including the user-typed `message`, `userAgent`, window `location` and (optionally) a screenshot.
The screenshot tool allows the user to select an area of the screen, add annotations etc.

feat: introduce eox-feedback element

---

elements/layout/src/main.js

This PR adds a height/width based on the provided CSS vars also for implicit rows & columns.

fix: set height for implicit rows/columns

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/src/helpers/index.js
elements/jsonform/src/main.js

This PR forces all external links (starting with `http[...]`) to be opened in new tabs. JSONEditor uses DOM purify internally to purify HTML in titles and descriptions (see https://github.com/search?q=repo%3Ajson-editor%2Fjson-editor%20purify&type=code), but doesn't allow modifying the settings needed (see e.g. https://github.com/cure53/DOMPurify/issues/317#issuecomment-470429778). Therefore, we brute-force all links to external ones, independent of what the form creator has set as link target.

fix: transform external links to target "blank"

---

elements/itemfilter/src/style.eox.js

This fixes a regression regarding the radio buttons.

fix(style): radio button display

---

elements/layout/src/main.js

In Vue.js (and potentially other frameworks that rely on virtual DOM), initially `parentElement` is `null` for the `eox-layout-item`, causing the layout to break on first render (subsequent updates were working correctly).
This PR introduces a check if `parentElement` is defined, and if not, triggers the rendering only after one tick (after a `setTimeout`).

fix: check if parentElement exists before rendering

---

elements/chart/package.json
package-lock.json

This reverts commit 9ffa851c4117e658ab7c874fa6ed0a3152e14125.
This PR reverts the updates of the vega group since it was causing issues with typescript (see https://github.com/EOX-A/EOxElements/pull/1694)

chore: Revert "chore(deps): bump the vega group with 3 updates (#1646)"

---

elements/jsonform/src/custom-inputs/minmax.js
elements/jsonform/stories/public/basicSchema.json

added passing of step to the minmax custom input for jsonform (only possitive integer input allowed in downstream library)

fix: add possibility to pass step to minmax custom filter

---

elements/drawtools/src/methods/draw/init-selection.js
elements/drawtools/src/methods/draw/on-draw-end.js
elements/drawtools/stories/multi-feature-select.js
elements/drawtools/stories/select-feature.js

This PR addresses the issue of losing the select interactions when users of `eox-map` update the json layer with the `layerId` passed to the drawtools. This PR mirrors the interactions to `EOxMap.layers` making up to the user to either reuse the interactions from there or remove it. Further more, there are minor error handling fixes.

Fix: Mirror selection interaction changes to json layers

---

elements/map/src/helpers/generate.js
elements/map/src/methods/map/setters.js

- Prevent reduntant `min/max` zoom level when the current value is already the same and which was causing some weird setting issue in `storytelling`
- And one minor `null` check in opacity setter
- https://github.com/EOX-A/EOxElements/pull/1633
https://github.com/user-attachments/assets/486134d6-0d1b-40ba-b21f-584e572852ea

Fix: Prevent redundant `min/max` zoom setting when the current `min/max` zoom level is already the same

---

elements/drawtools/src/components/list.js
elements/drawtools/src/main.js
elements/drawtools/stories/multi-feature-select.js
elements/drawtools/test/cases/feature-list.js

- We can now use two attribute to assign list title for each `feature`.
- `featureNameKey` can be used to get the value from `property` 
- `featureName` can be used to add an incremental title using `featureName` with `featureNumber`
- If `featureNameKey` is not available  `featureName` will be automatically taken.

Feat: Show selected feature title from some property value 

---

elements/storytelling/src/helpers/render-html-string.js
elements/storytelling/src/main.js
elements/storytelling/src/style.eox.js
elements/storytelling/stories/markdown-editor.js

- Added overlay content on top of `eox-map`
- Any content after `## ` will be added inside overlay content section
```
Some random description text
Some more content 
```
- User can position it using passing the following classes - 
- `overlay-br` Bottom Right
- `overlay-bl` Bottom left 
- `overlay-tr` Top Right
- `overlay-tl` Top Left 
- By `default ` the position will be Bottom Right

feat: overlay content on top of map

---

elements/map/src/methods/map/setters.js

This PR optimizes the `config` setter to apply all properties at once using `Object.assign()` instead of setting each property individually, preventing the firing of a setter for each of that properties.

fix: optimize config setter to not cause triggers for each property

---

elements/drawtools/src/components/list.js

This adds support for nested properties / property paths for `featureNameKey`. Example:
```
[...]
.featureNameKey=${"deeply.nested.property"}
[...]
```

feat: support nested properties for featureNameKey

---

elements/drawtools/src/components/controller.js
elements/drawtools/src/enums/test.js
elements/drawtools/src/style.eox.js
elements/drawtools/test/cases/copy-geo-json-editor.js

This PR adds a toggle for the editor by default, in order to harmonize it with the "import features" button.
https://github.com/user-attachments/assets/47fd44a5-130c-4c90-b8c3-29c2839914ac

feat: toggle editor on/off

---

elements/drawtools/src/components/list.js
elements/drawtools/src/methods/list/delete-feature.js
elements/drawtools/test/cases/feature-list.js

This PR adds a small fix that ensures the `drawupdate` event is also triggered when a single feature is deleted from the list. Previously it only triggered after drawing and discarding all features.

fix: emit drawupdate event when deleting single feature

---

elements/drawtools/src/main.js
elements/drawtools/src/methods/draw/create-select-handler.js
elements/drawtools/src/methods/draw/discard-drawing.js
elements/drawtools/src/methods/draw/handle-layer-id.js
elements/drawtools/src/methods/draw/init-layer.js
elements/drawtools/src/methods/draw/init-selection.js
elements/drawtools/src/methods/draw/on-draw-end.js
elements/drawtools/src/methods/draw/start-drawing.js
elements/drawtools/test/_mockMap.js
elements/jsonform/src/custom-inputs/spatial/editor.js
package-lock.json

This PR attempts to solve an issue with disconnecting and then (re-)connecting the `eox-drawtools`, as it is done e.g. in `eox-jsonform`. When the jsonform is updated and the drawtools are disconnected, they previously were left in a broken state that could not be reconnected properly, causing issues with using the drawtools inside a jsonform.
Here, a `resetLayer` method is added inside drawtools which resets the drawLayer on connection if it already exists; also a check is added to `eox-jsonform` to re-enable drawing if the user was currently drawing before the reset.

fix: disconnect/connect drawtools

---

elements/jsonform/src/helpers/editor.js

This PR adds small error badges for the "categories" format, displaying the current number of validation errors for each tab.
https://github.com/user-attachments/assets/85f1db81-fbfd-4b10-b5b0-3f656c8dd49b

feat: show number of validation errors per tab

---

elements/drawtools/src/methods/draw/discard-drawing.js

- Added a check to prevent removal of the `event` when it's triggered by a `selection-based` interaction. Previously, this was unintentionally removing the `event` even in draw-based components, which caused issues with highlighting `draw-based` features.

Fix: discarding feature removing highlight event also for draw based drawtool 

---

elements/itemfilter/src/components/filters/text.js
elements/itemfilter/src/helpers/capitalize.js
elements/itemfilter/src/helpers/filter-client.js
elements/itemfilter/src/helpers/highlighting.js
elements/itemfilter/src/helpers/index.js
elements/itemfilter/src/helpers/merge-highlight-indices.js
elements/itemfilter/src/methods/itemfilter/create-filter.js
elements/itemfilter/src/methods/results/create.js
elements/itemfilter/src/style.eox.js

- Added functionality to select the item which exactly matches the indicator when pressing the `return`.
-  Improved the `fuse` options so that it works on long strings
- Removed weird `text-transform` issue on highlight text 
- Improved the logic of `duplicate` string creation based on cleaning highlight indices. 
https://github.com/user-attachments/assets/8d9c992d-7572-42b1-9595-85adc03effa2

Fix: fuzzy search matching and highlighting

---

cypress/e2e/storybook.cy.js
demo.stories.js
package.json

- updated `npm run test:all` to `npm run styles && npm run test:component; npm run test:e2e` to run the e2e tests even if a component test fails (doesn't affect CI but allows better testing locally)
- updated `cypress/e2e/storybook.cy.js` to run all storybook e2e tests if `CI_PATHS_CHANGED` is empty (that env variable os only available on CI, meaning this change won't affect CI but will allow storybook e2e tests to run locally)

fix: run all tests with `npm run test:all`

---

elements/timecontrol/src/main.js

Added UTC to displayformat creation to make sure UTC time string is returned and not localized string.

fix: making sure time string is returned as UTC and not localized

---

elements/storytelling/src/enums/plugin.js
elements/storytelling/stories/markdown-editor.js

Fixes a regression caused by https://github.com/EOX-A/EOxElements/pull/1805, as mentioned in #1819.
The `prevent-scroll` attribute is now set by default, unless the story creator explicitly wants to remove it.

fix: set prevent-scroll true as default for map tours

---

elements/layercontrol/src/helpers/update-url.js

Ensure that array values (`{ key: [1,2,3]}`) in url parameters are encoded as `key=1&key=2&key=3` instead of `key=1,2,3`.
- Didn't find any test file where this behaviour was tested. Please let me know where a test should be added.

fix: handle array values in update-url helper

---

elements/jsonform/src/helpers/editor.js
elements/jsonform/src/main.js

This PR changes the class/id of the editing toggle switch from `.switch-button` to `#properties-editing-switch`, since it was causing conflicts with another `.switch-button` in eox-storytelling.

fix: rename switch class/id to prevent conflicts with other elements

---

elements/storytelling/src/style.eox.js

This fixes the spacing between sections:
- the spacing on desktop was reduced from over 3rem to 2rem
- when toggling off the editor, the separator line is removed to preview the story how it will actually look like (previously, the line was present if editing was enabled, even though the editor was switched off, resulting in a discrepancy between editing mode an viewing mode

fix(style): section spacing with/without editing mode

---

elements/itemfilter/src/helpers/get-value.js
elements/itemfilter/src/main.js

This PR adds support for functions additonal to property paths for `titleProeprty`, `subTitleProperty`, `imageProperty`.
Example:
```js
// itemfilter config
titleProperty: "id",
subTitleProperty: (item) => `Cloud cover: ${item.properties['eo:cloud_cover'].toFixed(1)}%`
```

feat: support callback functions for title, subTitle and image properties

---

elements/itemfilter/src/main.js
elements/itemfilter/src/methods/results/create.js

This PR adds support for `mouseenter:result` and `mouseleave:result` events. These are triggered when result items are hovered.

feat: emit mouseenter and mouseleave events on results

---

elements/layercontrol/src/components/layer-group.js

customeditorinterfaces was not being passed to all control options
N/A

fix: missing passing of customEditorInterfaces
