EOX-A/EOxElements

packages/map-tooltip/README.md, packages/map-tooltip/src/MapToolTip.vue
* allow passing a property filter to the tooltip
* update readme
=> allow passing a property filter to the tooltip (#25)

packages/map-tooltip/src/MapToolTip.vue
=> hide tooltop on mouse leave

packages/charts/src/Charts.vue
=> Fix charts tooltip

docs/.vuepress/components/ChartsBasic.vue, packages/charts/src/Charts.vue
=> Automatically stretch chart height

elements/itemfilter/src/main.ts, elements/itemfilter/test/config.cy.ts
Adds tests for the itemfilter config:
- enable/disable search bar
- enable/disable highlight
- exclusive/non-exclusive filter boxes
=> Initial Itemfilter config tests

elements/map/src/draw.ts
Adds modify interaction to draw
=> feat: add modify interaction

elements/timecontrol/examples/index.html, elements/timecontrol/package.json, elements/timecontrol/src/main.ts, elements/timecontrol/src/style.ts, package-lock.json
=> Timecontrol slider

elements/layercontrol/examples/index.html, elements/layercontrol/src/main.ts
This PR adds a way to define "optional" layers that are not initially rendered in the control list, but can be added optionally.
=> Optional layers

elements/map/examples/index.html, elements/map/src/select.ts, elements/map/test/drawInteraction.cy.ts, elements/map/test/drawInteraction.json, elements/map/test/general.cy.ts, elements/map/test/general.html, elements/map/test/hoverInteraction.cy.ts, elements/map/test/hoverInteraction.json, elements/map/test/imageWmsLayer.cy.ts, elements/map/test/imageWmsLayer.json, elements/map/test/tileWmsLayer.cy.ts, elements/map/test/tileWmsLayer.json, elements/map/test/vectorLayer.cy.ts, elements/map/test/vectorTilesLayer.cy.ts, elements/map/test/vectorTilesLayer.json
This PR brings adaptations to the existing tests to implement the newly proposed JSON-structure. Vector Styling is reduced to a minimum at the moment until we have clarification about the direction of style functions.
=> adaptations to new json structure

elements/map/src/controls.ts, elements/map/test/controls.cy.ts
This PR restores the possibility to define simple controls (without options) as Array.
=> Controls as Array

elements/layercontrol/examples/index.html, elements/layercontrol/index.html, elements/layercontrol/package.json, elements/layercontrol/src/main.ts, elements/layercontrol/src/style.eox.ts, elements/layercontrol/src/style.ts, package-lock.json
This PR adds
- exclusive layers (only one of them can be selected at a time)
- better sorting animation
- clean way of repeating DOM items (repeat directive instead of map directive)
- new examples
=> Layercontrol/main v.0.5.0

elements/layercontrol/README.md, elements/layercontrol/package.json, elements/layercontrol/src/main.ts, package-lock.json
This PR brings some needed updates to the readme, as wall as some fallback settings for when certain attributes are not provided.
=> Layercontrol v0.6.1

elements/itemfilter/examples/index.html, elements/itemfilter/package.json, elements/itemfilter/src/filters/_expandcontainer.ts, elements/itemfilter/src/filters/multiselect.ts, elements/itemfilter/src/filters/range.ts, elements/itemfilter/src/filters/select.ts, elements/itemfilter/src/filters/spatial.ts, elements/itemfilter/src/filters/text.ts, elements/itemfilter/src/global.d.ts, elements/itemfilter/src/main.ts, elements/itemfilter/src/style.eox.ts, elements/itemfilter/src/style.ts, package-lock.json, utils/styles/button.ts
This update brings a major styling improvement
=> Itemfilter v0.8.0

elements/itemfilter/package.json, elements/itemfilter/src/global.d.ts, elements/itemfilter/src/main.ts, elements/itemfilter/src/style.eox.ts, package-lock.json
This PR introduces a new filter feature (featured filters are rendered in a plain div instead of an expandable details panel), and exposes some previously private properties to be used from a hosting app.
=> Itemfilter v0.8.1

elements/map/main.ts, elements/map/package.json, elements/map/src/center.ts, elements/map/src/controls.ts, elements/map/src/generate.ts, elements/map/src/tooltip.ts, elements/map/tsconfig.json, package-lock.json
This PR introduces lit as framework to create the custom element(s) and handle attribution/property synchronization
=> Map v0.4.0

elements/itemfilter/index.html, elements/itemfilter/package.json, elements/itemfilter/src/filters/multiselect.ts, elements/itemfilter/src/filters/select.ts, elements/itemfilter/src/filters/spatial.ts, elements/itemfilter/src/main.ts, elements/itemfilter/src/style.eox.ts, elements/itemfilter/test/state.cy.ts, package-lock.json
This PR fixes rendering of the map by waiting for the next tick (using setTimeout), and introduces a `styleOverride` proeprty for easier element styling from the parent app. Also, the programmatically selected result is now displayed correctly.
=> Itemfilter v0.8.3

elements/map/package.json, elements/map/src/generate.ts, elements/map/test/stacLayer.cy.ts, elements/map/test/stacLayer.json, package-lock.json
This PR adds the ol-stac package for automatic rendering of STAC layers. Thanks @m-mohr for this package!
=> Add ol-stac

elements/map/main.ts, elements/map/package.json, package-lock.json
This PR introduces the sync/compare functionality which allows to sync one map view to another. It also introduces a new custom element `eox-map-compare` for easy comparison of two maps.
=> Map v0.5.1

elements/layercontrol/package.json, elements/layercontrol/src/main.ts, elements/layercontrol/test/_mockMap.ts, elements/layercontrol/test/general.cy.ts, package-lock.json
This PR introduces a fix for the collection change listener: it now also is observed inside layer groups. Fixes #211 .
=> Layercontrol v0.6.6

elements/layercontrol/CHANGELOG.md, elements/layercontrol/index.html, elements/layercontrol/src/main.ts, elements/layercontrol/src/style.eox.ts, elements/layercontrol/test/_mockMap.ts, elements/layercontrol/test/general.cy.ts
This pull request adds a delete button for layers and groups along with a Cypress test which checks if the entry was actually removed in both the map and the layer picker.
=> Remove map layers and groups

elements/stacinfo/package.json, elements/stacinfo/src/main.ts, elements/stacinfo/src/style.eox.ts, package-lock.json, utils/styles/button.ts
This PR introduces a small addition to render scientific citations in a special way in the footer, including a copy button to copy the formatted text.
=> Stacinfo v0.1.2

elements/map/src/generate.ts, elements/map/test/general.cy.ts
=> Don't mutate original layer array

elements/map/package.json, package-lock.json
This update includes a fix for temporary selection layers: https://github.com/EOX-A/EOxElements/pull/289
=> Map updates

elements/layercontrol/src/components/layerTools.js, utils/styles/button.ts
=> fix: removed icon highlight on hover

elements/stacinfo/src/main.ts
inspired by https://github.com/EOX-A/EOxElements/pull/386 adding styleoverride to stacinfo
=> fix: add styleOverride prop to stacinfo

.storybook/preview.js, elements/map/main.ts
This PR improves documentation for `eox-map` and rendering of autodoc blocks in general.
Closes https://github.com/EOX-A/EOxElements/issues/286
Closes #454
=> chore(docs): improve documentation

elements/layercontrol/src/components/add-layers.js, elements/layercontrol/src/components/layer-tools.js, elements/layercontrol/src/methods/add-layer/open-close-tab.js, elements/layercontrol/test/cases/layer-update/add-external-layer.js
- `unstyled` issues in layercontrol `tools` and `add-layers`
- Some jsdocs fixes
- Async cypress test failing again at one more place.
=> Hotfix: Layercontrol unstyled, jsdocs and cypress test fix

elements/layercontrol/test/cases/layer-update/add-external-layer.js
- Final Solution for Failing API Requests in Cypress Tests
- Implemented an interceptor to mock API requests with a dummy foo response.
- Rewrote the code to enhance asynchronous compatibility.
- Resolved input typing issues during browser interruptions by using force: true.
- Repeatedly ran tests locally and conducted 10 test iterations on GA.
=> Fix: Layercontrol external API test fail

elements/map/package.json, package-lock.json
Update broken `ol-stac` dependency causing a failing build: https://github.com/m-mohr/ol-stac/commit/fcd44af2f3da869b75d106258596d336000cc07e
=> chore(deps): update ol-stac package

elements/timecontrol/src/main.ts, elements/timecontrol/timecontrol.stories.js
Make play button in the time control removable via `disablePlay` component property.
Closes #609
=> feat: add a `disablePlay` property to disable the play button

elements/timecontrol/src/enums/index.js, elements/timecontrol/src/enums/test.js, elements/timecontrol/test/_mockMap.js, elements/timecontrol/test/cases/change-time.js, elements/timecontrol/test/cases/index.js, elements/timecontrol/test/cases/load-timecontrol.js, elements/timecontrol/test/general.cy.js, elements/timecontrol/timecontrol.stories.js
This PR adds some initial test cases for the timecontrol element (to be expanded in future).
=> chore(test): add initial test cases

elements/jsonform/src/enums/index.js, elements/jsonform/src/enums/test.js, elements/jsonform/test/cases/index.js, elements/jsonform/test/cases/load-jsonform.js, elements/jsonform/test/general.cy.js
This adds an initial test case for the `eox-jsonform` element.
=> chore(test): add initial test case

elements/drawtools/src/components/controller.js, elements/drawtools/src/components/list.js, elements/drawtools/src/enums/draw.js, elements/drawtools/src/enums/index.js, elements/drawtools/src/enums/test.js, elements/drawtools/src/helpers/copy-text-to-clipboard.js, elements/drawtools/src/helpers/generate-upload-events.js, elements/drawtools/src/helpers/index.js, elements/drawtools/src/main.js, elements/drawtools/src/methods/draw/discard-drawing.js, elements/drawtools/src/methods/draw/emit-drawn-features.js, elements/drawtools/src/methods/draw/index.js, elements/drawtools/src/methods/draw/init-layer.js, elements/drawtools/src/methods/draw/on-draw-end.js, elements/drawtools/src/methods/draw/start-drawing.js, elements/drawtools/src/style.eox.js, elements/drawtools/stories/drawtools.stories.js, elements/drawtools/stories/import-features.js, elements/drawtools/stories/index.js, elements/drawtools/test/_mockMap.js, elements/drawtools/test/cases/copy-geo-json-editor.js, elements/drawtools/test/cases/index.js, elements/drawtools/test/general.cy.js, elements/map/helpers.ts, elements/map/main.ts, elements/map/src/draw.ts, elements/map/src/select.ts, package-lock.json, utils/styles/input.css
Allowing users to upload/paste shape files directly to the `drawtools`
- Two attributes have been introduced for specific functionalities:
- `show-editor`: Activates the editor within `drawtools`.
- `import-features`: Enables the capability to upload, drag and drop files into `drawtools`.
- Users have the ability to upload, paste, or drag and drop three primary shapefile formats:
- GeoJSON
- TopoJSON
- KML
- However, the primary shapefile format supported by the editor is `GeoJSON`. Any uploaded files in different formats will be automatically converted to `GeoJSON`.
- The editor includes a copy button to facilitate the copying of GeoJSON data.
- All OpenLayers (OL) implementations are encapsulated within `eox-map`, eliminating the need to import any `OL` files directly into …
=> feat: feature editor with shape upload and drag&drop

elements/drawtools/package.json, elements/layercontrol/package.json, elements/map/package.json, elements/timecontrol/package.json, package-lock.json
This PR updates the `ol` package across multiple elements to version `^9.0.0.`.
=> chore(deps): update ol versions to ^9.0.0

elements/layercontrol/package.json, elements/layercontrol/stories/layercontrol.stories.dev.js, elements/layercontrol/stories/layercontrol.stories.js, package-lock.json
Small update of devDependencies in order to fix storybook pipeline.
=> chore: add devdependencies for map and jsonform

elements/storytelling/package.json, elements/storytelling/src/main.js, elements/storytelling/src/markdown-it-plugin/index.js, elements/storytelling/src/markdown-it-plugin/markdown-it-config.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/index.js, elements/storytelling/stories/markdown-basic-config.js, elements/storytelling/stories/storytelling.stories.js, elements/storytelling/test/cases/index.js, elements/storytelling/test/cases/load-markdown-config.js, elements/storytelling/test/general.cy.js, package-lock.json
- Add basic config using markdown 
```markdown
---
nav: false
id: 123
slug: abc-xyz
---
```
- Generated using custom plugin called `markdown-it-config`
- Only one markdown formatter can be declared anything after that won't be rendered. 
- We can view config by passing `show-config` into `EOxStoryTelling`
- Right now only one `key` is used to control the `StoryTelling` i.e. `nav` which is used to override global `show-nav` state
- Automatically convert to it's own data-type with the help of ` js-yaml`
- More `keys` can be added to future as we develop.
=> Feat: Basic frontmatter config

elements/storytelling/src/main.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/markdown-basic-config.js, elements/storytelling/stories/navigation.js, elements/storytelling/stories/storytelling.stories.js, utils/styles/main.css
=> Feat: Basic styling for storytelling

.storybook/main.js, elements/map/map.stories.js, package-lock.json, package.json
This PR upgrades Storybook and its addons to `v8.0.0`. One of the main improvements is the mobile layout.
=> chore(deps): upgrade storybook to v8

elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/index.js, elements/storytelling/stories/markdown-sections.js, elements/storytelling/stories/storytelling.stories.js, elements/storytelling/test/cases/load-sections.js
- Generate section on basis of `h2` (##) and `as` attribute 
- If `as` is mentioned with `h2` the section will be based on the value provided in the attribute 
```markdown
<esa-main-section id="section-earthcode-portal" class="section-wrap" title="EarthCODE Portal"></esa-main-section>
```
- If just `h2` is provided without `as` attributes - section is made with `div`
```markdown
<div class="section-wrap" id="section-earthcode-portal" title="EarthCODE Portal"></div>
```
- If just `h2` is provided with any default tag in `as` attributes
```markdown
```
https://github.com/EOX-A/EOxElements/assets/10809211/269072c8-73a4-4edb-b4b1-7e46bcc944e7
=> Feat: Storytelling section

elements/storytelling/src/enums/editor.js, elements/storytelling/src/helpers/editor.js
- Implemented import and export using SimpleMD toolbar.
- Added two tools for export and import 
- Works alongside editor.
https://github.com/EOX-A/EOxElements/assets/10809211/9a232c39-ba1c-4746-a85a-48d873cea433
=> Feat: Export/Import for storytelling editor 

elements/storytelling/src/helpers/index.js, elements/storytelling/src/helpers/misc.js, elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/src/main.js, elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/index.js, elements/storytelling/stories/markdown-fallback.js, elements/storytelling/stories/markdown-lightbox.js, elements/storytelling/stories/storytelling.stories.js, elements/storytelling/test/cases/index.js, elements/storytelling/test/cases/load-lightbox.js, elements/storytelling/test/general.cy.js
- Implemented `lightbox` with StoryTelling
- Works only with images
- Need to provide `no-shadow` to enable it. 
- Will enable on all images other than `hero`
https://github.com/EOX-A/EOxElements/assets/10809211/15ea6b59-2470-4fc0-9b16-680960b6fb0c
=> feat: lightbox for images

elements/jsonform/src/style.eox.js, elements/storytelling/src/components/editor.js, elements/storytelling/src/enums/editor.js, elements/storytelling/src/enums/index.js, elements/storytelling/src/enums/sample.js, elements/storytelling/src/helpers/editor.js, elements/storytelling/src/helpers/index.js, elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/src/main.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/markdown-hero-with-nav.js, elements/storytelling/test/cases/load-editor.js
- Added custom section selection popup on click on add button between sections and add button on editor
- Inside the popup we can categorise the section based on it's type
- Added EOx json-form to generate fields for markdown editor and user can customise the value of markdown before inserting it into editor.
- Field update not added to the basic category. 
https://github.com/EOX-A/EOxElements/assets/10809211/48801b37-6e60-43f6-bcee-6aec23130fe5
=> Feat: Section adding popup

README.md
This adds a readme section regarding how to set up a new element.
=> chore(docs): add readme section regarding bootstrapping new elements

elements/map/main.ts, elements/map/test/configObject.cy.ts
=> feat: config getter transforming native OL state

elements/jsonform/src/main.js, elements/storytelling/src/components/editor.js, elements/storytelling/src/enums/editor.js, elements/storytelling/src/helpers/editor.js, elements/storytelling/src/helpers/index.js, elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/src/main.js, elements/storytelling/src/markdown-it-plugin/markdown-it-decorate-improved.js, elements/storytelling/src/style.eox.js, elements/storytelling/stories/markdown-editor.js, elements/storytelling/stories/markdown-hero-with-nav.js, elements/storytelling/test/cases/load-editor.js, elements/storytelling/test/cases/load-error.js, package-lock.json, package.json
=> Fix: Misc bug fixes on SToryTelling before v1 release

elements/storytelling/src/helpers/validator.js, package-lock.json
- Fixed STAC based validator using Joi
=> Fix: Validator fixed for STAC based layer using joi 

elements/map/helpers.ts, elements/map/main.ts, elements/map/package.json, elements/map/src/controls/Geolocation.ts, elements/map/src/draw.ts, elements/map/src/generate.ts, elements/map/src/select.ts, elements/map/test/drawInteraction.cy.ts, elements/map/test/updateStyle.cy.ts, elements/map/test/vectorLayer.cy.ts, elements/map/test/vectorTilesLayer.cy.ts, package-lock.json
=> fix(deps): support `ol` version `9.2.5-dev.1719634408469`

elements/itemfilter/package.json, elements/itemfilter/src/components/itemfilter-container.js, elements/itemfilter/src/methods/container/handler.js, elements/itemfilter/src/style.eox.js, package-lock.json
This PR introduces a combination of `popover` ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API), [caniuse](https://caniuse.com/?search=popover)) and [floating-ui](https://floating-ui.com/) to achieve a top-layer dropdown.
With the native `popover` API, the dropdown can be rendered on top of every other content, and with the help of floating-ui the position is updated on scroll.
=> fix: top-level dropdown

elements/map/test/groupLayer.cy.ts
connected to https://github.com/EOX-A/EOxElements/issues/975
This PR adds additional tests for the group layer, testing reactivity of layers inside groups up to 2 levels deep.
=> chore: add additional groupLayer tests

elements/drawtools/package.json, elements/layercontrol/package.json, elements/timecontrol/package.json, package-lock.json
This PR updates the ol version in all dev dependencies to `^9.2.5-dev.1719634408469`.
=> chore(deps-dev): new ol version for dev dependencies

package-lock.json, package.json
This fixes the Storybook build error. See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#failed-to-resolve-import-storybookx-error
=> chore(deps-dev): add missing storybook dependencies

elements/itemfilter/src/components/itemfilter-container.js, elements/itemfilter/src/methods/container/index.js, elements/itemfilter/src/methods/container/init-popver.js
- Update event function when `inlineMode` attribute value changes from `false` <> `true`
=> Fix: Update event function to control inline mode state change

elements/timecontrol/src/main.js, elements/timecontrol/src/sliderticks.js, elements/timecontrol/tsconfig.json, utils/getElement.js
This PR adds some additional types in order to mitigate errors appearing during `npm run typecheck`.
=> chore: fix type errors

elements/itemfilter/src/helpers/chip-items.js, elements/itemfilter/src/methods/filters/range.js, elements/itemfilter/stories/inline-mode.js
- Chips should be combination of filter title + value, not key + value
- If range values are numerical (not date), don't convert to date in chips
=> Fix: Range value as numerical (not date) and chip text as title not key

elements/map/test/fixtures/eoxCapabilities.xml, elements/map/test/wmtsCapabilities.cy.ts
This PR fixes some problems with the fixture that seem to have happened during some refactoring. This fixes the interception of the XML as well as the XML itself (for some reason it was broken, now it is replaced with the current version of the EOx WMTS)
Additionally, this properly wraps the test in a `Cypress.Promise` and awaits the results of the tests after firing the events.
=> chore: fix wmtsCapabilities fixture & async test

elements/map/package.json, elements/map/test/wmtsCapabilities.cy.ts, package-lock.json
=> chore(deps): upgrade OL to 10.2.0

elements/itemfilter/src/helpers/map-layers.js, elements/layercontrol/src/enums/stories/index.js, elements/map/test/groupLayer.cy.ts
fix https://github.com/EOX-A/EOxElements/issues/1238
=> fix: update maps tiles url to public domain

elements/layercontrol/package.json, elements/layercontrol/src/components/layer-config.js, package-lock.json
Swapped debounce with throttle to make sure updates of style happen while interacting. Made throttle timestep depended on layerconfig type.
Closes #1170
=> feat: changed update of style to throttle

elements/itemfilter/src/components/filters/text.js, elements/itemfilter/src/methods/filters/text.js, elements/itemfilter/src/methods/itemfilter/create-filter.js, elements/itemfilter/src/style.eox.js, elements/itemfilter/stories/primary.js, elements/itemfilter/test/cases/general/index.js, elements/itemfilter/test/cases/general/validation.js, elements/itemfilter/test/general.cy.js
Added regex validation to the text filter. The validation object is set in the `filterObject`. Example:
`validation: {
pattern: ".{0,10}",
message: "Maximum 10 characters",
},`
https://github.com/user-attachments/assets/9bbc6e92-b296-47db-b175-cb13edc87c14
=> feat: regex text validation

elements/map/stories/index.js, elements/map/stories/map.stories.js, elements/map/stories/static-image.js
Adds a story for static image layer. Closes #1281.
=> chore(docs): add static image layer story

elements/drawtools/src/methods/draw/discard-drawing.js, elements/drawtools/src/methods/draw/init-selection.js, elements/drawtools/test/_mockMap.js, elements/drawtools/test/cases/index.js, elements/drawtools/test/cases/set-layer-id.js, elements/drawtools/test/general.cy.js
Cleaning up after https://github.com/EOX-A/EOxElements/pull/1334; see also https://github.com/EOX-A/EOxElements/issues/1333.
=> chore: remove timeout according to fixed bug in eox-map

elements/chart/package.json, elements/drawtools/package.json, elements/geosearch/package.json, elements/itemfilter/package.json, elements/jsonform/package.json, elements/layercontrol/package.json, elements/map/package.json, elements/stacinfo/package.json, elements/storytelling/package.json, elements/timecontrol/package.json, package-lock.json
Aligns all the lit versions of all the elements
=> chore(deps): update lit version

elements/drawtools/package.json, elements/itemfilter/package.json, elements/layercontrol/package.json, elements/stacinfo/global.d.ts, elements/stacinfo/package.json, elements/storytelling/package.json, elements/timecontrol/package.json, package-lock.json, utils/package.json
This PR includes a few dependency updates and some cleanups left to do after the previous "un-bundling" PR(s). Some dependencies were still a devDependency instead of a peerDependency by mistake.
Also some elements used "latest" as a dependency version which caused version mismatches, in some cases this could be removed, in some cases it was replaced with `"*"`.
=> chore(deps): update dev & peer dependencies

utils/styles/main.css
This adds some very basic code block styling as we currently don't have anything in our utils package (and therefore also not in storytelling).
=> feat: add basic code styling

utils/styles/main.css
This moves the font-family to the correct location...
=> fix: move font-family

elements/storytelling/src/style.eox.js
- Changed nav content position from bottom to top in mobile
=> Fix: Changed nav content position from bottom to top 

elements/timecontrol/test/cases/load-date-format.js, elements/timecontrol/test/general.cy.js
This PR fixes a test that assumed the current date as test value
=> chore(test): fix tests

elements/chart/package.json, elements/drawtools/package.json, elements/geosearch/package.json, elements/itemfilter/package.json, elements/jsonform/package.json, elements/layercontrol/package.json, elements/layercontrol/src/components/layer-tools.js, elements/layercontrol/src/components/layer.js, elements/map/package.json, elements/stacinfo/package.json, elements/storytelling/package.json, elements/storytelling/src/style.eox.js, elements/timecontrol/package.json, elements/timecontrol/src/style.eox.js, package-lock.json
Updating `elements-utils` package to latest and adapting imports.
=> fix(deps): update elements-utils package

elements/jsonform/src/style.eox.js
This PR fixes the alignment of the label for boolean type inputs.
=> fix(style): checkbox label alignment

elements/jsonform/src/helpers/editor.js, elements/jsonform/src/style.eox.js, elements/jsonform/stories/jsonform.stories.js, elements/jsonform/stories/validation.js
This PR is a major rewrite of the `eox-jsonform` styling to adjust margins, paddings, alignments, buttons etc.
It also introduces two new CSS variables:
- `--eox-panel-border`: useful if one would like to hide the default border
- `--eox-panel-spacing`: useful if one would like to adjust the spacing of the panels
By default, the panel border is now enabled, since it makes it much easier to digest complex forms. For very simple forms, however, the new CSS variables offer a way to simplify the layout a lot.
=> feat(style): styling overhaul

elements/drawtools/src/main.js, elements/drawtools/src/methods/draw/init-layer.js, elements/drawtools/src/methods/draw/init-selection.js, elements/drawtools/stories/multi-feature-select.js
https://github.com/user-attachments/assets/04cd6198-c0f2-46b9-abce-ef37dcdba406
=> Feat: Enable styling draw layer & hover and click interactions

elements/map/src/helpers/generate.js
=> fix: check interactions identifiers when updating a layer

elements/drawtools/package.json, elements/geosearch/package.json, elements/jsonform/package.json, elements/layercontrol/package.json, elements/storytelling/package.json, elements/timecontrol/package.json
Updates to TypeScript type definition paths based on our newly tsconfig structure:
* [`elements/drawtools/package.json`](diffhunk://#diff-29c018b661ee25665aa2b70e52e545b1f3a7ff6adc91f8737ed8a913831eafcaL19-R26): Updated `types` and `typesVersions` paths to `./types/drawtools/src/main.d.ts` and `./types/drawtools/src/*` respectively.
* [`elements/geosearch/package.json`](diffhunk://#diff-ac2e96a8642c4c6f90b2942106a1d11d759387354b82662f9c3c047b611aad18L15-R22): Updated `types` and `typesVersions` paths to `./types/geosearch/src/main.d.ts` and `./types/geosearch/src/*` respectively.
* [`elements/jsonform/package.json`](diffhunk://#diff-141eb91b4cba1a4d631aaa2704be3f93e70f579c5ed506f62a360a07f7256353L19-R26): Updated `types` and `typesVersions` paths to `./types/jsonform/src/main.d.ts` and …
=> fix: TypeScript exports

elements/storytelling/src/enums/custom-editor-interface.js, elements/storytelling/src/enums/sample.js, elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/stories/markdown-editor.js
- Addition of `data-fallback-src` also part of upload `event`
```js
// Updated event code
<eox-storytelling
@upload:file=${(e) => {
const detail = e.detail;
const { file, update } = detail;
// API reuest with upload api 
someAPIFunc(file).then(({url, fallbackUrl}) => {
update(url, fallbackUrl);
}).catch(() => {
const error = {
message: "some error message"
}
update(null, null, error); 
});
}}
></eox-storytelling>
```
- Added `input` event for `src` URL `input`
=> Fix: changes related to upload editor 

elements/storytelling/src/main.js
This adds automatic parsing and linking of urls and email addresses using the markdown-it `linkify` setting.
=> feat: auto-parse & create links

elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/stories/markdown-editor.js
- `fallback-src` not working due to the wrong `dom` check. Replaced it with `renderRoot` check
=> Fix: `fallback-src` not working due to `no-shadow` check skip

elements/itemfilter/src/methods/results/create.js, elements/itemfilter/src/style.eox.js
This PR fixes smaller issues with the itemfilter card display.
=> fix: card cursor & placeholder

elements/layout/src/main.js
=> fix: Render element when it's connected

.github/workflows/preview_release.yml
This PR introduces continuous preview releases of packages powered by [pkg.pr.new](https://github.com/stackblitz-labs/pkg.pr.new).
=> feat(CI): add preview releases

elements/itemfilter/src/components/chips.js, elements/itemfilter/src/components/itemfilter-container.js, elements/itemfilter/src/style.eox.js
This PR fixes a styling issue of the inline-mode, as the shadow root was hindering the styles being applied properly. Also removed a border, added a shadow instead, and fixed the scrollbar display.
=> fix(style): inline mode container and popover

elements/storytelling/src/helpers/editor.js, elements/storytelling/src/helpers/render-html-string.js, elements/storytelling/src/style.eox.js
- Styling issue 
- the top button should not be shown, since it does not make sense to add a section above the hero
- the bottom button is cut off (not overflowing the hero) and the icon is not centered
- Changed `add section` logic due to weird event triggering and adding new section in random indexes of the story.
=> Fix: add section button logic issue and styling
